
// ==================================================================
// DocumentRegisterTaskObservers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class DocumentRegisterTaskObservers :
    global::Sungero.Workflow.Client.TaskObservers, global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("2932f285-d458-4046-a392-87f6a50ba8ee");

    public override global::System.Guid TypeGuid
    {
      get { return global::GD.DCSGovernmentModule.Client.DocumentRegisterTaskObservers.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "GD.DCSGovernmentModule.IDocumentRegisterTaskObservers, Sungero.Domain.Interfaces"; }
    }

    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversState State
    {
      get
      {
        return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskObserversState(this);
    }

    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversInfo Info
    {
      get
      {
        return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversInfo)base.Info;
      }
    }










    #endregion

    #region Methods

    #endregion

    #region Framework events





    #endregion

    #region Constructors




    public DocumentRegisterTaskObservers()
    {








    }

    #endregion

  }
}
