
// ==================================================================
// RegistrationAssignmentState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class RegistrationAssignmentState : 
    global::Sungero.Workflow.Shared.AssignmentState, global::GD.DCSGovernmentModule.IRegistrationAssignmentState
  {
    public RegistrationAssignmentState(global::GD.DCSGovernmentModule.IRegistrationAssignment entity) : base(entity) { }

    public new global::GD.DCSGovernmentModule.IRegistrationAssignmentPropertyStates Properties
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignmentPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentPropertyStates(entity);
    }


    public new global::GD.DCSGovernmentModule.IRegistrationAssignmentControlStates Controls
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignmentControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentControlStates(entity);
    }

    public new global::GD.DCSGovernmentModule.IRegistrationAssignmentPageStates Pages
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignmentPageStates)base.Pages; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPageStates CreatePageStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentPageStates(entity);
    }

    #region Workflow attachments extention

    public global::GD.DCSGovernmentModule.IRegistrationAssignmentAttachmentStates Attachments { get { return (global::GD.DCSGovernmentModule.IRegistrationAssignmentAttachmentStates)this.AttachmentStates; }}

      protected override global::Sungero.Workflow.Interfaces.IWorkflowEntityAttachmentStates CreateAttachmentStates(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) 
      {
        return new RegistrationAssignmentAttachmentStates(entity);
      }

    #endregion
  }

  #region Workflow attachments extention

    public class RegistrationAssignmentAttachmentStates :
      global::Sungero.Workflow.Shared.AssignmentAttachmentStates, global::GD.DCSGovernmentModule.IRegistrationAssignmentAttachmentStates
    {
      public global::Sungero.Workflow.Interfaces.IAttachmentGroupState DocumentGroup 
      {
        get
        {
          return this.AttachmentGroups.GetAttachmentGroupState(global::System.Guid.Parse("f0f24f20-d363-400d-b530-ac25aa6f90fc"));
        }
      }
      public global::Sungero.Workflow.Interfaces.IAttachmentGroupState OtherGroup 
      {
        get
        {
          return this.AttachmentGroups.GetAttachmentGroupState(global::System.Guid.Parse("fbc37bb6-22db-47fa-b1b4-3f375bfabd21"));
        }
      }


      protected internal RegistrationAssignmentAttachmentStates(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity) { }
    }

  #endregion

  public class RegistrationAssignmentControlStates : 
    global::Sungero.Workflow.Shared.AssignmentControlStates, global::GD.DCSGovernmentModule.IRegistrationAssignmentControlStates
  {

    protected internal RegistrationAssignmentControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }
  public class RegistrationAssignmentPageStates : 
    global::Sungero.Workflow.Shared.AssignmentPageStates, global::GD.DCSGovernmentModule.IRegistrationAssignmentPageStates
  {

    protected internal RegistrationAssignmentPageStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class RegistrationAssignmentPropertyStates : 
    global::Sungero.Workflow.Shared.AssignmentPropertyStates, global::GD.DCSGovernmentModule.IRegistrationAssignmentPropertyStates
  {
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IEmployee> Registrar 
            {
              get { return this.InternalRegistrar; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IEmployee> InternalRegistrar
            {
              get { return this.GetPropertyState<global::Sungero.Company.IEmployee>("Registrar"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IBusinessUnit> BusinessUnit 
            {
              get { return this.InternalBusinessUnit; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IBusinessUnit> InternalBusinessUnit
            {
              get { return this.GetPropertyState<global::Sungero.Company.IBusinessUnit>("BusinessUnit"); }
            }


    protected internal RegistrationAssignmentPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

// ==================================================================
// RegistrationAssignmentInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class RegistrationAssignmentInfo : 
    global::Sungero.Workflow.Shared.AssignmentInfo, global::GD.DCSGovernmentModule.IRegistrationAssignmentInfo
  {
    public RegistrationAssignmentInfo(global::System.Type entityType) : base(entityType) { }

    public new global::GD.DCSGovernmentModule.IRegistrationAssignmentPropertiesInfo Properties
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignmentPropertiesInfo)base.Properties; }
    }

    public new global::GD.DCSGovernmentModule.IRegistrationAssignmentActionsInfo Actions
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignmentActionsInfo)base.Actions; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentPropertiesInfo(entityType);
    }

    protected override global::Sungero.Domain.Shared.IEntityActionsInfo CreateEntityActionsInfo(global::System.Type entityType)
    {
      return new global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentActionsInfo(entityType);
    }
  }

  public class RegistrationAssignmentPropertiesInfo : 
    global::Sungero.Workflow.Shared.AssignmentPropertiesInfo, global::GD.DCSGovernmentModule.IRegistrationAssignmentPropertiesInfo
  {
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Company.IEmployeeInfo, global::Sungero.Company.IEmployee> Registrar 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Registrar");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Company.IEmployeeInfo, global::Sungero.Company.IEmployee>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Company.IBusinessUnitInfo, global::Sungero.Company.IBusinessUnit> BusinessUnit 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("BusinessUnit");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Company.IBusinessUnitInfo, global::Sungero.Company.IBusinessUnit>(propertyMetadata);
          }
        }


    protected internal RegistrationAssignmentPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

  public class RegistrationAssignmentActionsInfo : 
    global::Sungero.Workflow.Shared.AssignmentActionsInfo, global::GD.DCSGovernmentModule.IRegistrationAssignmentActionsInfo
  {
        public global::Sungero.Domain.Shared.IActionInfo ChangeLeadingDocument 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("ChangeLeadingDocument")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo Register 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("Register")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo Decline 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("Decline")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo ToRegistrar 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("ToRegistrar")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo ToBusinessUnit 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("ToBusinessUnit")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo ToRequest 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("ToRequest")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo ToLetter 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("ToLetter")); }
        }
        public global::Sungero.Domain.Shared.IActionInfo Registration 
        {
          get { return new global::Sungero.Domain.Shared.ActionInfo(this.GetActionMetadata("Registration")); }
        }


    protected internal RegistrationAssignmentActionsInfo(global::System.Type entityType) : base(entityType) { }
  }
}

// ==================================================================
// RegistrationAssignmentHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule
{
  public partial class RegistrationAssignmentSharedHandlers : global::Sungero.Workflow.AssignmentSharedHandlers, IRegistrationAssignmentSharedHandlers
  {
    private global::GD.DCSGovernmentModule.IRegistrationAssignment _obj
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignment)this.Entity; }
    }
    public virtual void RegistrarChanged(global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentRegistrarChangedEventArgs e) { }


    public virtual void BusinessUnitChanged(global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentBusinessUnitChangedEventArgs e) { }



    #region Workflow attachments extention

        public virtual void DocumentGroupCreated(global::Sungero.Workflow.Interfaces.AttachmentCreatedEventArgs e) { }
        public virtual void DocumentGroupAdded(global::Sungero.Workflow.Interfaces.AttachmentAddedEventArgs e) { }
        public virtual void DocumentGroupDeleted(global::Sungero.Workflow.Interfaces.AttachmentDeletedEventArgs e) { }

        public virtual void OtherGroupCreated(global::Sungero.Workflow.Interfaces.AttachmentCreatedEventArgs e) { }
        public virtual void OtherGroupAdded(global::Sungero.Workflow.Interfaces.AttachmentAddedEventArgs e) { }
        public virtual void OtherGroupDeleted(global::Sungero.Workflow.Interfaces.AttachmentDeletedEventArgs e) { }


    #endregion

    public RegistrationAssignmentSharedHandlers(global::GD.DCSGovernmentModule.IRegistrationAssignment entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// RegistrationAssignmentResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared.RegistrationAssignment
{
  /// <summary>
  /// Represents RegistrationAssignment resources.
  /// </summary>
  public class RegistrationAssignmentResources : global::Sungero.Workflow.Shared.Assignment.AssignmentResources, global::GD.DCSGovernmentModule.RegistrationAssignment.IRegistrationAssignmentResources
  {
    public virtual global::CommonLibrary.LocalizedString SelectLeadingDocument
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "SelectLeadingDocument");
      }
    }

    public virtual global::CommonLibrary.LocalizedString SelectLeadingDocumentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "SelectLeadingDocument", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString Document
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "Document");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DocumentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "Document", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString UnableChangeMainDocument
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "UnableChangeMainDocument");
      }
    }

    public virtual global::CommonLibrary.LocalizedString UnableChangeMainDocumentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "UnableChangeMainDocument", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString SuccessfullyDocument
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "SuccessfullyDocument");
      }
    }

    public virtual global::CommonLibrary.LocalizedString SuccessfullyDocumentFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "SuccessfullyDocument", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DocumentNotRegistered
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "DocumentNotRegistered");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DocumentNotRegisteredFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "DocumentNotRegistered", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RegisterText
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "RegisterText");
      }
    }

    public virtual global::CommonLibrary.LocalizedString RegisterTextFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "RegisterText", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString NeedFillReasonsForRejection
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "NeedFillReasonsForRejection");
      }
    }

    public virtual global::CommonLibrary.LocalizedString NeedFillReasonsForRejectionFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "NeedFillReasonsForRejection", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DeclineText
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "DeclineText");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DeclineTextFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "DeclineText", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString NeedFillBusinessUnit
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "NeedFillBusinessUnit");
      }
    }

    public virtual global::CommonLibrary.LocalizedString NeedFillBusinessUnitFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "NeedFillBusinessUnit", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString NeedFillRegistrar
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "NeedFillRegistrar");
      }
    }

    public virtual global::CommonLibrary.LocalizedString NeedFillRegistrarFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "NeedFillRegistrar", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ForwardedToRegistrar
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "ForwardedToRegistrar");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ForwardedToRegistrarFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "ForwardedToRegistrar", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ForwardedToBusinessUnit
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "ForwardedToBusinessUnit");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ForwardedToBusinessUnitFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "ForwardedToBusinessUnit", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RegistrarNotFoundRequest
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "RegistrarNotFoundRequest");
      }
    }

    public virtual global::CommonLibrary.LocalizedString RegistrarNotFoundRequestFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "RegistrarNotFoundRequest", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ReformLetterToRequest
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "ReformLetterToRequest");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ReformLetterToRequestFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "ReformLetterToRequest", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString ReformRequestToLetter
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "ReformRequestToLetter");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ReformRequestToLetterFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "ReformRequestToLetter", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RegistrarNotFoundLetter
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment) , "RegistrarNotFoundLetter");
      }
    }

    public virtual global::CommonLibrary.LocalizedString RegistrarNotFoundLetterFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IRegistrationAssignment), "RegistrarNotFoundLetter", false, args);
    }

  }
}

// ==================================================================
// RegistrationAssignmentSharedFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Shared
{
  public partial class RegistrationAssignmentFunctions : global::Sungero.Workflow.Shared.AssignmentFunctions
  {
    private global::GD.DCSGovernmentModule.IRegistrationAssignment _obj
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignment)this.Entity; }
    }

    public RegistrationAssignmentFunctions(global::GD.DCSGovernmentModule.IRegistrationAssignment entity) : base(entity) { }
  }
}

// ==================================================================
// RegistrationAssignmentFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Functions
{
  internal static class RegistrationAssignment
  {
  }
}

// ==================================================================
// RegistrationAssignmentFilterState.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Shared.RegistrationAssignment
{

  public class RegistrationAssignmentFilterInfo : global::Sungero.Workflow.Shared.Assignment.AssignmentFilterInfo,
    global::GD.DCSGovernmentModule.IRegistrationAssignmentFilterInfo
  {
  }

  public class RegistrationAssignmentFilterState : global::Sungero.Workflow.Shared.Assignment.AssignmentFilterState,
    global::GD.DCSGovernmentModule.IRegistrationAssignmentFilterState
  {



    public new GD.DCSGovernmentModule.IRegistrationAssignmentFilterInfo Info
    {
      get
      {
        return (GD.DCSGovernmentModule.IRegistrationAssignmentFilterInfo) base.Info;
      }
    }
    protected override global::Sungero.Domain.Shared.IFilterInfo CreateFilterInfo()
    {
      return new GD.DCSGovernmentModule.Shared.RegistrationAssignment.RegistrationAssignmentFilterInfo();
    }

  }
}

// ==================================================================
// RegistrationAssignmentSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class RegistrationAssignmentSharedPublicFunctions : global::GD.DCSGovernmentModule.Shared.IRegistrationAssignmentSharedPublicFunctions
  {
  }
}

// ==================================================================
// RegistrationAssignmentAttachmentGroups.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{

  public class RegistrationAssignmentDocumentGroupAttachments : global::Sungero.Workflow.Shared.WorkflowEntityAttachmentGroupDecorator,
    global::GD.DCSGovernmentModule.IRegistrationAssignmentDocumentGroupAttachments
  {
      public global::System.Collections.Generic.ICollection<global::Sungero.Docflow.IIncomingDocumentBase> IncomingDocumentBases
      { 
        get 
        { 
          return this.GetAttachmentGroupCollection<global::Sungero.Docflow.IIncomingDocumentBase>();
        } 
      }


    public RegistrationAssignmentDocumentGroupAttachments(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity, "f0f24f20-d363-400d-b530-ac25aa6f90fc") { }
  }

  public class RegistrationAssignmentOtherGroupAttachments : global::Sungero.Workflow.Shared.WorkflowEntityAttachmentGroupDecorator,
    global::GD.DCSGovernmentModule.IRegistrationAssignmentOtherGroupAttachments
  {

    public RegistrationAssignmentOtherGroupAttachments(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity, "fbc37bb6-22db-47fa-b1b4-3f375bfabd21") { }
  }

}

// ==================================================================
// RegistrationAssignmentExtendedSchemeVersions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.RegistrationAssignment
{

    /// <summary>
    /// Список версий схемы.
    /// </summary>
    public static class LayerSchemeVersions
    {
      public static readonly global::Sungero.Workflow.Shared.ExtendedSchemeVersion V1 =
        new global::Sungero.Workflow.Shared.ExtendedSchemeVersion(1, global::System.Guid.Parse("0745199f-eaac-4875-8563-40ed1e5ce317"));
}

    public static class TaskExtensions
    {
      /// <summary>
      /// Получить версию схемы запущенной задачи.
      /// </summary>
      /// <param name="task">Задача.</param>
      /// <returns>Версия схемы запущенной задачи.</returns>
      public static global::Sungero.Workflow.Shared.ExtendedSchemeVersion GetStartedSchemeVersion(this global::Sungero.Workflow.ITask task)
      {
        return global::Sungero.Workflow.Shared.OverriddenTaskHelper.FindLayerSchemeVersionForTask(task,
          global::System.Guid.Parse("d574cc38-2354-46fa-85d6-686c525f182b"));
      }
    }

}
