
// ==================================================================
// Module.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{
  public partial class DCSGovernmentModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("25a0577f-66cf-4bdc-bc9a-768ec24e062e"); }
    }

    public override string Name
    {
      get { return "GD.DCSGovernment"; }
    }

    public override void RegisterTypes()
    {
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("d0432c80-f060-494d-89dc-bfb89a1d828f"), new GD.DCSGovernment.Shared.ProcessingRuleIncomingLetterInfo(typeof(global::GD.DCSGovernment.IProcessingRuleIncomingLetter)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernment.Client.IProcessingRuleIncomingLetterClientPublicFunctions, global::GD.DCSGovernment.Client.ProcessingRuleIncomingLetterClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernment.Shared.IProcessingRuleIncomingLetterSharedPublicFunctions, global::GD.DCSGovernment.Shared.ProcessingRuleIncomingLetterSharedPublicFunctions>();
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("46c35676-cf07-4eaa-b0ed-eb5f263ecc1f"), new GD.DCSGovernment.Shared.ProcessingRuleIncomingLetterPerformersInfo(typeof(global::GD.DCSGovernment.IProcessingRuleIncomingLetterPerformers)));


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState, global::GD.DCSGovernment.Shared.ProcessingRuleIncomingLetter.ProcessingRuleIncomingLetterFilterState>();



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernment.Module.DCTSIntegration.Client.IModuleClientPublicFunctions, global::GD.DCSGovernment.Module.DCTSIntegration.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernment.Module.DCTSIntegration.Shared.IModuleSharedPublicFunctions, global::GD.DCSGovernment.Module.DCTSIntegration.Shared.ModuleSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernment.Client.IModuleClientPublicFunctions, global::GD.DCSGovernment.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernment.Shared.IModuleSharedPublicFunctions, global::GD.DCSGovernment.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
