
// ==================================================================
// ProcessingRuleDocBaseEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{ 
}

// ==================================================================
// ProcessingRuleDocBaseHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment
{

  public partial class ProcessingRuleDocBaseFilteringClientHandler
    : global::DirRX.DCTSIntegration.ProcessingRuleDocBaseFilteringClientHandler
  {
    private global::GD.DCSGovernment.IProcessingRuleDocBaseFilterState _filter
    {
      get
      {
        return (GD.DCSGovernment.IProcessingRuleDocBaseFilterState)this.Filter;
      }
    }

    public ProcessingRuleDocBaseFilteringClientHandler(global::GD.DCSGovernment.IProcessingRuleDocBaseFilterState filter)
    : base(filter)
    {
    }

    protected ProcessingRuleDocBaseFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
      base.ValidateFilterPanel(e);
    }
  }


  public partial class ProcessingRuleDocBaseClientHandlers : global::DirRX.DCTSIntegration.ProcessingRuleDocBaseClientHandlers
  {
    private global::GD.DCSGovernment.IProcessingRuleDocBase _obj
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleDocBase)this.Entity; }
    }

    public ProcessingRuleDocBaseClientHandlers(global::GD.DCSGovernment.IProcessingRuleDocBase entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// ProcessingRuleDocBaseClientFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernment.Client
{
  public partial class ProcessingRuleDocBaseFunctions : global::DirRX.DCTSIntegration.Client.ProcessingRuleDocBaseFunctions
  {
    private global::GD.DCSGovernment.IProcessingRuleDocBase _obj
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleDocBase)this.Entity; }
    }

    public ProcessingRuleDocBaseFunctions(global::GD.DCSGovernment.IProcessingRuleDocBase entity) : base(entity) { }
  }
}

// ==================================================================
// ProcessingRuleDocBaseFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Functions
{
  internal static class ProcessingRuleDocBase
  {
    /// <redirect project="GD.DCSGovernment.Shared" type="GD.DCSGovernment.Shared.ProcessingRuleDocBaseFunctions" />
    internal static  void SetRequiredProperties(global::GD.DCSGovernment.IProcessingRuleDocBase processingRuleDocBase)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)processingRuleDocBase).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetRequiredProperties", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="GD.DCSGovernment.Shared" type="GD.DCSGovernment.Shared.ProcessingRuleDocBaseFunctions" />
    internal static  void SetPropertiesVisibility(global::GD.DCSGovernment.IProcessingRuleDocBase processingRuleDocBase)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)processingRuleDocBase).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetPropertiesVisibility", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

  }
}

// ==================================================================
// ProcessingRuleDocBaseClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{
  public class ProcessingRuleDocBaseClientPublicFunctions : global::GD.DCSGovernment.Client.IProcessingRuleDocBaseClientPublicFunctions
  {
  }
}

// ==================================================================
// ProcessingRuleDocBaseActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{
  public partial class ProcessingRuleDocBaseActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleDocBaseActions
  {
    private global::GD.DCSGovernment.IProcessingRuleDocBase _obj { get { return (global::GD.DCSGovernment.IProcessingRuleDocBase)this.Entity; } }
    public ProcessingRuleDocBaseActions(global::GD.DCSGovernment.IProcessingRuleDocBase entity) : base(entity) { }
  }

  public partial class ProcessingRuleDocBaseCollectionActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleDocBaseCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::GD.DCSGovernment.IProcessingRuleDocBase> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::GD.DCSGovernment.IProcessingRuleDocBase>(this.Entities); }
    }
  }

  public partial class ProcessingRuleDocBaseCollectionBulkActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleDocBaseCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int64> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class ProcessingRuleDocBaseAnyChildEntityActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleDocBaseAnyChildEntityActions
  {
  }

  public partial class ProcessingRuleDocBaseAnyChildEntityCollectionActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleDocBaseAnyChildEntityCollectionActions
  {
  }



}
