
// ==================================================================
// DocumentRegisterTaskState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class DocumentRegisterTaskState : 
    global::Sungero.Workflow.Shared.TaskState, global::GD.DCSGovernmentModule.IDocumentRegisterTaskState
  {
    public DocumentRegisterTaskState(global::GD.DCSGovernmentModule.IDocumentRegisterTask entity) : base(entity) { }

    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskPropertyStates Properties
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskPropertyStates(entity);
    }


    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskControlStates Controls
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskControlStates(entity);
    }

    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskPageStates Pages
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskPageStates)base.Pages; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPageStates CreatePageStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskPageStates(entity);
    }

    #region Workflow attachments extention

    public global::GD.DCSGovernmentModule.IDocumentRegisterTaskAttachmentStates Attachments { get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskAttachmentStates)this.AttachmentStates; }}

      protected override global::Sungero.Workflow.Interfaces.IWorkflowEntityAttachmentStates CreateAttachmentStates(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) 
      {
        return new DocumentRegisterTaskAttachmentStates(entity);
      }

    #endregion
  }

  #region Workflow attachments extention

    public class DocumentRegisterTaskAttachmentStates :
      global::Sungero.Workflow.Shared.TaskAttachmentStates, global::GD.DCSGovernmentModule.IDocumentRegisterTaskAttachmentStates
    {
      public global::Sungero.Workflow.Interfaces.IAttachmentGroupState DocumentGroup 
      {
        get
        {
          return this.AttachmentGroups.GetAttachmentGroupState(global::System.Guid.Parse("f0f24f20-d363-400d-b530-ac25aa6f90fc"));
        }
      }
      public global::Sungero.Workflow.Interfaces.IAttachmentGroupState OtherGroup 
      {
        get
        {
          return this.AttachmentGroups.GetAttachmentGroupState(global::System.Guid.Parse("fbc37bb6-22db-47fa-b1b4-3f375bfabd21"));
        }
      }


      protected internal DocumentRegisterTaskAttachmentStates(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity) { }
    }

  #endregion

  public class DocumentRegisterTaskControlStates : 
    global::Sungero.Workflow.Shared.TaskControlStates, global::GD.DCSGovernmentModule.IDocumentRegisterTaskControlStates
  {

    protected internal DocumentRegisterTaskControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }
  public class DocumentRegisterTaskPageStates : 
    global::Sungero.Workflow.Shared.TaskPageStates, global::GD.DCSGovernmentModule.IDocumentRegisterTaskPageStates
  {

    protected internal DocumentRegisterTaskPageStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class DocumentRegisterTaskPropertyStates : 
    global::Sungero.Workflow.Shared.TaskPropertyStates, global::GD.DCSGovernmentModule.IDocumentRegisterTaskPropertyStates
  {
            public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversCollectionPropertyState<global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers> Observers
            {
              get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversCollectionPropertyState<global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers>)base.Observers; }
            }

            protected override global::Sungero.Workflow.ITaskObserversCollectionPropertyState<global::Sungero.Workflow.ITaskObservers> CreateObserversState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskObserversCollectionPropertyState<global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers>(entity, propertyName);
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::DirRX.DCTSIntegration.IProcessingRuleBase> ProcessingRule 
            {
              get { return this.InternalProcessingRule; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::DirRX.DCTSIntegration.IProcessingRuleBase> InternalProcessingRule
            {
              get { return this.GetPropertyState<global::DirRX.DCTSIntegration.IProcessingRuleBase>("ProcessingRule"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IIncomingLetter> Letter 
            {
              get { return this.InternalLetter; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.RecordManagement.IIncomingLetter> InternalLetter
            {
              get { return this.GetPropertyState<global::Sungero.RecordManagement.IIncomingLetter>("Letter"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::GD.CitizenRequests.IRequest> Request 
            {
              get { return this.InternalRequest; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::GD.CitizenRequests.IRequest> InternalRequest
            {
              get { return this.GetPropertyState<global::GD.CitizenRequests.IRequest>("Request"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IEmployee> Registrar 
            {
              get { return this.InternalRegistrar; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IEmployee> InternalRegistrar
            {
              get { return this.GetPropertyState<global::Sungero.Company.IEmployee>("Registrar"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IBusinessUnit> BusinessUnit 
            {
              get { return this.InternalBusinessUnit; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IBusinessUnit> InternalBusinessUnit
            {
              get { return this.GetPropertyState<global::Sungero.Company.IBusinessUnit>("BusinessUnit"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Boolean?> WasRedirected 
            {
              get { return this.GetPropertyState<global::System.Boolean?>("WasRedirected"); }
            }


    protected internal DocumentRegisterTaskPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

// ==================================================================
// DocumentRegisterTaskInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class DocumentRegisterTaskInfo : 
    global::Sungero.Workflow.Shared.TaskInfo, global::GD.DCSGovernmentModule.IDocumentRegisterTaskInfo
  {
    public DocumentRegisterTaskInfo(global::System.Type entityType) : base(entityType) { }

    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskPropertiesInfo Properties
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskPropertiesInfo(entityType);
    }

  }

  public class DocumentRegisterTaskPropertiesInfo : 
    global::Sungero.Workflow.Shared.TaskPropertiesInfo, global::GD.DCSGovernmentModule.IDocumentRegisterTaskPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertiesInfo> Observers
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("Observers");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertiesInfo>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::DirRX.DCTSIntegration.IProcessingRuleBaseInfo, global::DirRX.DCTSIntegration.IProcessingRuleBase> ProcessingRule 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("ProcessingRule");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::DirRX.DCTSIntegration.IProcessingRuleBaseInfo, global::DirRX.DCTSIntegration.IProcessingRuleBase>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.RecordManagement.IIncomingLetterInfo, global::Sungero.RecordManagement.IIncomingLetter> Letter 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Letter");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.RecordManagement.IIncomingLetterInfo, global::Sungero.RecordManagement.IIncomingLetter>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::GD.CitizenRequests.IRequestInfo, global::GD.CitizenRequests.IRequest> Request 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Request");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::GD.CitizenRequests.IRequestInfo, global::GD.CitizenRequests.IRequest>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Company.IEmployeeInfo, global::Sungero.Company.IEmployee> Registrar 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Registrar");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Company.IEmployeeInfo, global::Sungero.Company.IEmployee>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Company.IBusinessUnitInfo, global::Sungero.Company.IBusinessUnit> BusinessUnit 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("BusinessUnit");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Company.IBusinessUnitInfo, global::Sungero.Company.IBusinessUnit>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IBooleanPropertyInfo WasRedirected 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.BooleanPropertyMetadata>("WasRedirected");
             return new global::Sungero.Domain.Shared.BooleanPropertyInfo(propertyMetadata);
          }
        }


    protected internal DocumentRegisterTaskPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}

// ==================================================================
// DocumentRegisterTaskHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule
{
  public partial class DocumentRegisterTaskSharedHandlers : global::Sungero.Workflow.TaskSharedHandlers, IDocumentRegisterTaskSharedHandlers
  {
    private global::GD.DCSGovernmentModule.IDocumentRegisterTask _obj
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTask)this.Entity; }
    }
    public virtual void ProcessingRuleChanged(global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskProcessingRuleChangedEventArgs e) { }


    public virtual void LetterChanged(global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskLetterChangedEventArgs e) { }


    public virtual void RequestChanged(global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskRequestChangedEventArgs e) { }


    public virtual void RegistrarChanged(global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskRegistrarChangedEventArgs e) { }


    public virtual void BusinessUnitChanged(global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskBusinessUnitChangedEventArgs e) { }


    public virtual void WasRedirectedChanged(global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs e) { }



    #region Workflow attachments extention

        public virtual void DocumentGroupCreated(global::Sungero.Workflow.Interfaces.AttachmentCreatedEventArgs e) { }
        public virtual void DocumentGroupAdded(global::Sungero.Workflow.Interfaces.AttachmentAddedEventArgs e) { }
        public virtual void DocumentGroupDeleted(global::Sungero.Workflow.Interfaces.AttachmentDeletedEventArgs e) { }

        public virtual void OtherGroupCreated(global::Sungero.Workflow.Interfaces.AttachmentCreatedEventArgs e) { }
        public virtual void OtherGroupAdded(global::Sungero.Workflow.Interfaces.AttachmentAddedEventArgs e) { }
        public virtual void OtherGroupDeleted(global::Sungero.Workflow.Interfaces.AttachmentDeletedEventArgs e) { }


    #endregion

    public DocumentRegisterTaskSharedHandlers(global::GD.DCSGovernmentModule.IDocumentRegisterTask entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// DocumentRegisterTaskResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared.DocumentRegisterTask
{
  /// <summary>
  /// Represents DocumentRegisterTask resources.
  /// </summary>
  public class DocumentRegisterTaskResources : global::Sungero.Workflow.Shared.Task.TaskResources, global::GD.DCSGovernmentModule.DocumentRegisterTask.IDocumentRegisterTaskResources
  {
    public virtual global::CommonLibrary.LocalizedString ReformDocumentError
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IDocumentRegisterTask) , "ReformDocumentError");
      }
    }

    public virtual global::CommonLibrary.LocalizedString ReformDocumentErrorFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IDocumentRegisterTask), "ReformDocumentError", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString DocumentRegisterTaskSubject
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IDocumentRegisterTask) , "DocumentRegisterTaskSubject");
      }
    }

    public virtual global::CommonLibrary.LocalizedString DocumentRegisterTaskSubjectFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IDocumentRegisterTask), "DocumentRegisterTaskSubject", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString CompleteMessageTemplate
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IDocumentRegisterTask) , "CompleteMessageTemplate");
      }
    }

    public virtual global::CommonLibrary.LocalizedString CompleteMessageTemplateFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IDocumentRegisterTask), "CompleteMessageTemplate", false, args);
    }

  }
}

// ==================================================================
// DocumentRegisterTaskSharedFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Shared
{
  public partial class DocumentRegisterTaskFunctions : global::Sungero.Workflow.Shared.TaskFunctions
  {
    private global::GD.DCSGovernmentModule.IDocumentRegisterTask _obj
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTask)this.Entity; }
    }

    public DocumentRegisterTaskFunctions(global::GD.DCSGovernmentModule.IDocumentRegisterTask entity) : base(entity) { }
  }
}

// ==================================================================
// DocumentRegisterTaskFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Functions
{
  internal static class DocumentRegisterTask
  {
  }
}

// ==================================================================
// DocumentRegisterTaskFilterState.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Shared.DocumentRegisterTask
{

  public class DocumentRegisterTaskFilterInfo : global::Sungero.Workflow.Shared.Task.TaskFilterInfo,
    global::GD.DCSGovernmentModule.IDocumentRegisterTaskFilterInfo
  {
  }

  public class DocumentRegisterTaskFilterState : global::Sungero.Workflow.Shared.Task.TaskFilterState,
    global::GD.DCSGovernmentModule.IDocumentRegisterTaskFilterState
  {



    public new GD.DCSGovernmentModule.IDocumentRegisterTaskFilterInfo Info
    {
      get
      {
        return (GD.DCSGovernmentModule.IDocumentRegisterTaskFilterInfo) base.Info;
      }
    }
    protected override global::Sungero.Domain.Shared.IFilterInfo CreateFilterInfo()
    {
      return new GD.DCSGovernmentModule.Shared.DocumentRegisterTask.DocumentRegisterTaskFilterInfo();
    }

  }
}

// ==================================================================
// DocumentRegisterTaskSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class DocumentRegisterTaskSharedPublicFunctions : global::GD.DCSGovernmentModule.Shared.IDocumentRegisterTaskSharedPublicFunctions
  {
  }
}

// ==================================================================
// DocumentRegisterTaskAttachmentGroups.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{

  public class DocumentRegisterTaskDocumentGroupAttachments : global::Sungero.Workflow.Shared.WorkflowEntityAttachmentGroupDecorator,
    global::GD.DCSGovernmentModule.IDocumentRegisterTaskDocumentGroupAttachments
  {
      public global::System.Collections.Generic.ICollection<global::Sungero.Docflow.IIncomingDocumentBase> IncomingDocumentBases
      { 
        get 
        { 
          return this.GetAttachmentGroupCollection<global::Sungero.Docflow.IIncomingDocumentBase>();
        } 
      }


    public DocumentRegisterTaskDocumentGroupAttachments(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity, "f0f24f20-d363-400d-b530-ac25aa6f90fc") { }
  }

  public class DocumentRegisterTaskOtherGroupAttachments : global::Sungero.Workflow.Shared.WorkflowEntityAttachmentGroupDecorator,
    global::GD.DCSGovernmentModule.IDocumentRegisterTaskOtherGroupAttachments
  {

    public DocumentRegisterTaskOtherGroupAttachments(global::Sungero.Workflow.Interfaces.IWorkflowEntity entity) : base(entity, "fbc37bb6-22db-47fa-b1b4-3f375bfabd21") { }
  }

}

// ==================================================================
// DocumentRegisterTaskExtendedSchemeVersions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.DocumentRegisterTask
{

    /// <summary>
    /// Список версий схемы.
    /// </summary>
    public static class LayerSchemeVersions
    {
      public static readonly global::Sungero.Workflow.Shared.ExtendedSchemeVersion V1 =
        new global::Sungero.Workflow.Shared.ExtendedSchemeVersion(1, global::System.Guid.Parse("0745199f-eaac-4875-8563-40ed1e5ce317"));
}

    public static class TaskExtensions
    {
      /// <summary>
      /// Получить версию схемы запущенной задачи.
      /// </summary>
      /// <param name="task">Задача.</param>
      /// <returns>Версия схемы запущенной задачи.</returns>
      public static global::Sungero.Workflow.Shared.ExtendedSchemeVersion GetStartedSchemeVersion(this global::Sungero.Workflow.ITask task)
      {
        return global::Sungero.Workflow.Shared.OverriddenTaskHelper.FindLayerSchemeVersionForTask(task,
          global::System.Guid.Parse("d574cc38-2354-46fa-85d6-686c525f182b"));
      }
    }

}
