
// ==================================================================
// ModuleSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Module.DCTSIntegration.Shared
{
  public partial class ModuleSharedPublicFunctions : global::GD.DCSGovernment.Module.DCTSIntegration.Shared.IModuleSharedPublicFunctions
  {
  }
}

// ==================================================================
// ModuleFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Module.DCTSIntegration.Functions
{
  internal static partial class Module
  {
    private static object GetFunctionsContainer()
    {
      return new global::GD.DCSGovernment.Module.DCTSIntegration.Shared.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType, global::Sungero.Metadata.ModuleMetadata finalModuleMetadatda)
    {
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      var methodInfo = moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static);
      return global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, null, null);
    }
  }
}
namespace GD.DCSGovernment.Module.DCTSIntegration.Shared
{
  public partial class ModuleFunctions: global::DirRX.DCTSIntegration.Shared.ModuleFunctions
  {

  }
}

// ==================================================================
// ModuleHyperlinks.g.cs
// ==================================================================

namespace GD.DCSGovernment.Module.DCTSIntegration
{
  public static class DCTSIntegrationClientFunctionHyperlinksExtensions
  {
  }
}

// ==================================================================
// ModuleFoldersFilterStates.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Module.DCTSIntegration.Shared
{
}

// ==================================================================
// ModuleResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Module.DCTSIntegration.Shared
{
  public class ModuleResources : global::DirRX.DCTSIntegration.Shared.ModuleResources, global::GD.DCSGovernment.Module.DCTSIntegration.IModuleResources
  {
    public virtual global::CommonLibrary.LocalizedString RequestRuleName
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(System.Guid.Parse("ead5cbd0-2ebd-4a37-91a1-ec3879648e9c")) , "RequestRuleName", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString RequestRuleNameFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(System.Guid.Parse("ead5cbd0-2ebd-4a37-91a1-ec3879648e9c")), "RequestRuleName", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RequestLineToSystem
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(System.Guid.Parse("ead5cbd0-2ebd-4a37-91a1-ec3879648e9c")) , "RequestLineToSystem", false);
      }
    }

    public virtual global::CommonLibrary.LocalizedString RequestLineToSystemFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetString(global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(System.Guid.Parse("ead5cbd0-2ebd-4a37-91a1-ec3879648e9c")), "RequestLineToSystem", false, args);
    }

  }
}

// ==================================================================
// ModuleWidgetParameters.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Module.DCTSIntegration.Shared
{  
}
