
// ==================================================================
// DocumentRegisterTaskEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{ 
  public class DocumentRegisterTaskProcessingRuleValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::DirRX.DCTSIntegration.IProcessingRuleBase>
  {
    public DocumentRegisterTaskProcessingRuleValueInputEventArgs(global::DirRX.DCTSIntegration.IProcessingRuleBase oldValue, global::DirRX.DCTSIntegration.IProcessingRuleBase newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

  public class DocumentRegisterTaskLetterValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.RecordManagement.IIncomingLetter>
  {
    public DocumentRegisterTaskLetterValueInputEventArgs(global::Sungero.RecordManagement.IIncomingLetter oldValue, global::Sungero.RecordManagement.IIncomingLetter newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

  public class DocumentRegisterTaskRequestValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::GD.CitizenRequests.IRequest>
  {
    public DocumentRegisterTaskRequestValueInputEventArgs(global::GD.CitizenRequests.IRequest oldValue, global::GD.CitizenRequests.IRequest newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

  public class DocumentRegisterTaskRegistrarValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Company.IEmployee>
  {
    public DocumentRegisterTaskRegistrarValueInputEventArgs(global::Sungero.Company.IEmployee oldValue, global::Sungero.Company.IEmployee newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

  public class DocumentRegisterTaskBusinessUnitValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Company.IBusinessUnit>
  {
    public DocumentRegisterTaskBusinessUnitValueInputEventArgs(global::Sungero.Company.IBusinessUnit oldValue, global::Sungero.Company.IBusinessUnit newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }


}

// ==================================================================
// DocumentRegisterTaskHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule
{

  public partial class DocumentRegisterTaskFilteringClientHandler
    : global::Sungero.Domain.EntityFilteringClientHandler
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::GD.DCSGovernmentModule.IDocumentRegisterTaskFilterState Filter { get; private set; }

    private global::GD.DCSGovernmentModule.IDocumentRegisterTaskFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public DocumentRegisterTaskFilteringClientHandler(global::GD.DCSGovernmentModule.IDocumentRegisterTaskFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected DocumentRegisterTaskFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }
  }


  public partial class DocumentRegisterTaskClientHandlers : global::Sungero.Workflow.TaskClientHandlers
  {
    private global::GD.DCSGovernmentModule.IDocumentRegisterTask _obj
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTask)this.Entity; }
    }

    public virtual void ProcessingRuleValueInput(global::GD.DCSGovernmentModule.Client.DocumentRegisterTaskProcessingRuleValueInputEventArgs e) { }


    public virtual void LetterValueInput(global::GD.DCSGovernmentModule.Client.DocumentRegisterTaskLetterValueInputEventArgs e) { }


    public virtual void RequestValueInput(global::GD.DCSGovernmentModule.Client.DocumentRegisterTaskRequestValueInputEventArgs e) { }


    public virtual void RegistrarValueInput(global::GD.DCSGovernmentModule.Client.DocumentRegisterTaskRegistrarValueInputEventArgs e) { }


    public virtual void BusinessUnitValueInput(global::GD.DCSGovernmentModule.Client.DocumentRegisterTaskBusinessUnitValueInputEventArgs e) { }


    public virtual void WasRedirectedValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public DocumentRegisterTaskClientHandlers(global::GD.DCSGovernmentModule.IDocumentRegisterTask entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// DocumentRegisterTaskClientFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Client
{
  public partial class DocumentRegisterTaskFunctions : global::Sungero.Workflow.Client.TaskFunctions
  {
    private global::GD.DCSGovernmentModule.IDocumentRegisterTask _obj
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTask)this.Entity; }
    }

    public DocumentRegisterTaskFunctions(global::GD.DCSGovernmentModule.IDocumentRegisterTask entity) : base(entity) { }
  }
}

// ==================================================================
// DocumentRegisterTaskFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Functions
{
  internal static class DocumentRegisterTask
  {
  }
}

// ==================================================================
// DocumentRegisterTaskClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class DocumentRegisterTaskClientPublicFunctions : global::GD.DCSGovernmentModule.Client.IDocumentRegisterTaskClientPublicFunctions
  {
  }
}

// ==================================================================
// DocumentRegisterTaskActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public partial class DocumentRegisterTaskActions : global::Sungero.Workflow.Client.TaskActions
  {
    private global::GD.DCSGovernmentModule.IDocumentRegisterTask _obj { get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTask)this.Entity; } }
    public DocumentRegisterTaskActions(global::GD.DCSGovernmentModule.IDocumentRegisterTask entity) : base(entity) { }
  }

  public partial class DocumentRegisterTaskCollectionActions : global::Sungero.Workflow.Client.TaskCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::GD.DCSGovernmentModule.IDocumentRegisterTask> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::GD.DCSGovernmentModule.IDocumentRegisterTask>(this.Entities); }
    }
  }

  public partial class DocumentRegisterTaskCollectionBulkActions : global::Sungero.Workflow.Client.TaskCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int64> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class DocumentRegisterTaskAnyChildEntityActions : global::Sungero.Workflow.Client.TaskAnyChildEntityActions
  {
  }

  public partial class DocumentRegisterTaskAnyChildEntityCollectionActions : global::Sungero.Workflow.Client.TaskAnyChildEntityCollectionActions
  {
  }



}
