
// ==================================================================
// ProcessingRuleRequestEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{ 
  public class ProcessingRuleRequestCorrespondentValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Parties.IPerson>
  {
    public ProcessingRuleRequestCorrespondentValueInputEventArgs(global::Sungero.Parties.IPerson oldValue, global::Sungero.Parties.IPerson newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }


  public class ProcessingRuleRequestDepartmentValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Company.IDepartment>
  {
    public ProcessingRuleRequestDepartmentValueInputEventArgs(global::Sungero.Company.IDepartment oldValue, global::Sungero.Company.IDepartment newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }


}

// ==================================================================
// ProcessingRuleRequestHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule
{

  public partial class ProcessingRuleRequestFilteringClientHandler
    : global::GD.DCSGovernment.ProcessingRuleDocBaseFilteringClientHandler
  {
    private global::GD.DCSGovernmentModule.IProcessingRuleRequestFilterState _filter
    {
      get
      {
        return (GD.DCSGovernmentModule.IProcessingRuleRequestFilterState)this.Filter;
      }
    }

    public ProcessingRuleRequestFilteringClientHandler(global::GD.DCSGovernmentModule.IProcessingRuleRequestFilterState filter)
    : base(filter)
    {
    }

    protected ProcessingRuleRequestFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
      base.ValidateFilterPanel(e);
    }
  }


  public partial class ProcessingRuleRequestClientHandlers : global::GD.DCSGovernment.ProcessingRuleDocBaseClientHandlers
  {
    private global::GD.DCSGovernmentModule.IProcessingRuleRequest _obj
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequest)this.Entity; }
    }

    public virtual void SubjectPatternValueInput(global::Sungero.Presentation.StringValueInputEventArgs e) { }


    public virtual void FillFromSubjectValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public virtual void CorrespondentValueInput(global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestCorrespondentValueInputEventArgs e) { }


    public virtual void IsAutoCalcCorrespondentValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }



    public virtual void FillFromFileNameValueInput(global::Sungero.Presentation.BooleanValueInputEventArgs e) { }


    public ProcessingRuleRequestClientHandlers(global::GD.DCSGovernmentModule.IProcessingRuleRequest entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// ProcessingRuleRequestClientFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Client
{
  public partial class ProcessingRuleRequestFunctions : global::GD.DCSGovernment.Client.ProcessingRuleDocBaseFunctions
  {
    private global::GD.DCSGovernmentModule.IProcessingRuleRequest _obj
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequest)this.Entity; }
    }

    public ProcessingRuleRequestFunctions(global::GD.DCSGovernmentModule.IProcessingRuleRequest entity) : base(entity) { }
  }
}

// ==================================================================
// ProcessingRuleRequestFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Functions
{
  internal static class ProcessingRuleRequest
  {
    /// <redirect project="GD.DCSGovernmentModule.Shared" type="GD.DCSGovernmentModule.Shared.ProcessingRuleRequestFunctions" />
    internal static  void SetPropertiesVisibility(global::GD.DCSGovernmentModule.IProcessingRuleRequest processingRuleRequest)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)processingRuleRequest).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetPropertiesVisibility", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="GD.DCSGovernmentModule.Shared" type="GD.DCSGovernmentModule.Shared.ProcessingRuleRequestFunctions" />
    internal static  void SetPropertiesAvailability(global::GD.DCSGovernmentModule.IProcessingRuleRequest processingRuleRequest)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)processingRuleRequest).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetPropertiesAvailability", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

    internal static class Remote
    {
      /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ProcessingRuleRequestFunctions" />
      internal static  global::GD.DCSGovernmentModule.IProcessingRuleRequest GetProcessingRule(global::System.Int64 id)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::GD.DCSGovernmentModule.IProcessingRuleRequest>(
          global::System.Guid.Parse("80051758-3f3f-4fcc-a772-f10c3c8e5bfd"),
          "GetProcessingRule(global::System.Int64)"
      , id);
      }
      /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ProcessingRuleRequestFunctions" />
      internal static  global::Sungero.Docflow.IOfficialDocument CreateDocument(global::GD.DCSGovernmentModule.IProcessingRuleRequest processingRuleRequest)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::Sungero.Docflow.IOfficialDocument>(
          global::System.Guid.Parse("80051758-3f3f-4fcc-a772-f10c3c8e5bfd"),
          "CreateDocument(global::GD.DCSGovernmentModule.IProcessingRuleRequest)"
          , processingRuleRequest);
      }

    }
  }
}

// ==================================================================
// ProcessingRuleRequestClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class ProcessingRuleRequestClientPublicFunctions : global::GD.DCSGovernmentModule.Client.IProcessingRuleRequestClientPublicFunctions
  {
  }
}

// ==================================================================
// ProcessingRuleRequestActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public partial class ProcessingRuleRequestActions : global::GD.DCSGovernment.Client.ProcessingRuleDocBaseActions
  {
    private global::GD.DCSGovernmentModule.IProcessingRuleRequest _obj { get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequest)this.Entity; } }
    public ProcessingRuleRequestActions(global::GD.DCSGovernmentModule.IProcessingRuleRequest entity) : base(entity) { }
  }

  public partial class ProcessingRuleRequestCollectionActions : global::GD.DCSGovernment.Client.ProcessingRuleDocBaseCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::GD.DCSGovernmentModule.IProcessingRuleRequest> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::GD.DCSGovernmentModule.IProcessingRuleRequest>(this.Entities); }
    }
  }

  public partial class ProcessingRuleRequestCollectionBulkActions : global::GD.DCSGovernment.Client.ProcessingRuleDocBaseCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int64> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class ProcessingRuleRequestAnyChildEntityActions : global::GD.DCSGovernment.Client.ProcessingRuleDocBaseAnyChildEntityActions
  {
  }

  public partial class ProcessingRuleRequestAnyChildEntityCollectionActions : global::GD.DCSGovernment.Client.ProcessingRuleDocBaseAnyChildEntityCollectionActions
  {
  }



}
