
// ==================================================================
// ProcessingRuleIncomingLetterEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{ 
}

// ==================================================================
// ProcessingRuleIncomingLetterHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment
{

  public partial class ProcessingRuleIncomingLetterFilteringClientHandler
    : global::DirRX.DCTSIntegration.ProcessingRuleIncomingLetterFilteringClientHandler
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState _filter
    {
      get
      {
        return (GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState)this.Filter;
      }
    }

    public ProcessingRuleIncomingLetterFilteringClientHandler(global::GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState filter)
    : base(filter)
    {
    }

    protected ProcessingRuleIncomingLetterFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
      base.ValidateFilterPanel(e);
    }
  }


  public partial class ProcessingRuleIncomingLetterClientHandlers : global::DirRX.DCTSIntegration.ProcessingRuleIncomingLetterClientHandlers
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetter _obj
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetter)this.Entity; }
    }

    public ProcessingRuleIncomingLetterClientHandlers(global::GD.DCSGovernment.IProcessingRuleIncomingLetter entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// ProcessingRuleIncomingLetterClientFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernment.Client
{
  public partial class ProcessingRuleIncomingLetterFunctions : global::DirRX.DCTSIntegration.Client.ProcessingRuleIncomingLetterFunctions
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetter _obj
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetter)this.Entity; }
    }

    public ProcessingRuleIncomingLetterFunctions(global::GD.DCSGovernment.IProcessingRuleIncomingLetter entity) : base(entity) { }
  }
}

// ==================================================================
// ProcessingRuleIncomingLetterFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Functions
{
  internal static class ProcessingRuleIncomingLetter
  {
  }
}

// ==================================================================
// ProcessingRuleIncomingLetterClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{
  public class ProcessingRuleIncomingLetterClientPublicFunctions : global::GD.DCSGovernment.Client.IProcessingRuleIncomingLetterClientPublicFunctions
  {
  }
}

// ==================================================================
// ProcessingRuleIncomingLetterActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{
  public partial class ProcessingRuleIncomingLetterActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleIncomingLetterActions
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetter _obj { get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetter)this.Entity; } }
    public ProcessingRuleIncomingLetterActions(global::GD.DCSGovernment.IProcessingRuleIncomingLetter entity) : base(entity) { }
  }

  public partial class ProcessingRuleIncomingLetterCollectionActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleIncomingLetterCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::GD.DCSGovernment.IProcessingRuleIncomingLetter> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::GD.DCSGovernment.IProcessingRuleIncomingLetter>(this.Entities); }
    }
  }

  public partial class ProcessingRuleIncomingLetterCollectionBulkActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleIncomingLetterCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int64> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class ProcessingRuleIncomingLetterAnyChildEntityActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleIncomingLetterAnyChildEntityActions
  {
  }

  public partial class ProcessingRuleIncomingLetterAnyChildEntityCollectionActions : global::DirRX.DCTSIntegration.Client.ProcessingRuleIncomingLetterAnyChildEntityCollectionActions
  {
  }



}
