
// ==================================================================
// Module.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server
{
  public partial class DCSGovernmentModuleModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("15db5ebc-a567-4d1a-b9d6-53fedc2030c0"); }
    }

    public override string Name
    {
      get { return "GD.DCSGovernmentModule"; }
    }

    public override void RegisterTypes()
    {
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Server.IModuleServerInitializationFunctions, global::GD.DCSGovernmentModule.Server.ModuleServerInitializationFunctions>();
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("d574cc38-2354-46fa-85d6-686c525f182b"), new GD.DCSGovernmentModule.Shared.DocumentRegisterTaskInfo(typeof(global::GD.DCSGovernmentModule.IDocumentRegisterTask)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Server.IDocumentRegisterTaskServerPublicFunctions, global::GD.DCSGovernmentModule.Server.DocumentRegisterTaskServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IDocumentRegisterTaskSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskSharedPublicFunctions>();
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("2932f285-d458-4046-a392-87f6a50ba8ee"), new GD.DCSGovernmentModule.Shared.DocumentRegisterTaskObserversInfo(typeof(global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers)));
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("80051758-3f3f-4fcc-a772-f10c3c8e5bfd"), new GD.DCSGovernmentModule.Shared.ProcessingRuleRequestInfo(typeof(global::GD.DCSGovernmentModule.IProcessingRuleRequest)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Server.IProcessingRuleRequestServerPublicFunctions, global::GD.DCSGovernmentModule.Server.ProcessingRuleRequestServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IProcessingRuleRequestSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestSharedPublicFunctions>();
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("3f8c9aa0-6e4f-4c0d-985c-9a0532c4d278"), new GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPerformersInfo(typeof(global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers)));
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("9a576448-4a40-4dc6-8969-de3c210aec6a"), new GD.DCSGovernmentModule.Shared.RegistrationAssignmentInfo(typeof(global::GD.DCSGovernmentModule.IRegistrationAssignment)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Server.IRegistrationAssignmentServerPublicFunctions, global::GD.DCSGovernmentModule.Server.RegistrationAssignmentServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IRegistrationAssignmentSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.IDocumentRegisterTaskFilterState, global::GD.DCSGovernmentModule.Shared.DocumentRegisterTask.DocumentRegisterTaskFilterState>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.IProcessingRuleRequestFilterState, global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequest.ProcessingRuleRequestFilterState>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.IRegistrationAssignmentFilterState, global::GD.DCSGovernmentModule.Shared.RegistrationAssignment.RegistrationAssignmentFilterState>();



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Server.IModuleServerPublicFunctions, global::GD.DCSGovernmentModule.Server.ModuleServerPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IModuleSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.ModuleSharedPublicFunctions>();
    }
  }
}

// ==================================================================
// ModuleHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server
{
}

// ==================================================================
// ModuleFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Functions
{
  internal static partial class Module
  {
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    [global::Sungero.Core.RemoteAttribute()]
    internal static global::Sungero.Docflow.IOfficialDocument RefreshDocument(global::Sungero.Docflow.IOfficialDocument document)
    {
      var __moduleId = new global::System.Guid("15db5ebc-a567-4d1a-b9d6-53fedc2030c0");
      var __finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(__moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(__moduleId));
      var __funcNamespace = "Server" == "ClientBase" ? __finalModuleMetadatda.ClientNamespace : __finalModuleMetadatda.ServerNamespace;
      var __typeName = __funcNamespace + ".ModuleFunctions, GD.DCSGovernmentModule.Server";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("RefreshDocument", new global::System.Type[]{typeof(global::Sungero.Docflow.IOfficialDocument)});
        return (global::Sungero.Docflow.IOfficialDocument)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{document});
      }
      else
      {
        return ((global::GD.DCSGovernmentModule.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server, __finalModuleMetadatda)).RefreshDocument(document);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    [global::Sungero.Core.RemoteAttribute()]
    internal static global::System.Boolean TryCompleteAssignmentSyncThenAsync(global::Sungero.Workflow.IAssignment assignment, global::Sungero.Core.Enumeration result)
    {
      var __moduleId = new global::System.Guid("15db5ebc-a567-4d1a-b9d6-53fedc2030c0");
      var __finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(__moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(__moduleId));
      var __funcNamespace = "Server" == "ClientBase" ? __finalModuleMetadatda.ClientNamespace : __finalModuleMetadatda.ServerNamespace;
      var __typeName = __funcNamespace + ".ModuleFunctions, GD.DCSGovernmentModule.Server";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("TryCompleteAssignmentSyncThenAsync", new global::System.Type[]{typeof(global::Sungero.Workflow.IAssignment), typeof(global::Sungero.Core.Enumeration)});
        return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{assignment, result});
      }
      else
      {
        return ((global::GD.DCSGovernmentModule.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server, __finalModuleMetadatda)).TryCompleteAssignmentSyncThenAsync(assignment, result);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::System.String CreateZipFromFile(global::System.String filePath)
    {
      var __moduleId = new global::System.Guid("15db5ebc-a567-4d1a-b9d6-53fedc2030c0");
      var __finalModuleMetadatda = global::Sungero.Metadata.MetadataExtension.GetFinal(global::Sungero.Metadata.Services.MetadataSearcher.FindModuleMetadata(__moduleId) ?? global::Sungero.Metadata.Services.MetadataSearcher.FindLayerModuleMetadata(__moduleId));
      var __funcNamespace = "Server" == "ClientBase" ? __finalModuleMetadatda.ClientNamespace : __finalModuleMetadatda.ServerNamespace;
      var __typeName = __funcNamespace + ".ModuleFunctions, GD.DCSGovernmentModule.Server";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("CreateZipFromFile", new global::System.Type[]{typeof(global::System.String)});
        return (global::System.String)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{filePath});
      }
      else
      {
        return ((global::GD.DCSGovernmentModule.Server.ModuleFunctions)GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType.Server, __finalModuleMetadatda)).CreateZipFromFile(filePath);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::Sungero.Parties.IPerson GetPersonByEmail(global::System.String email)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("GetPersonByEmail", new global::System.Type[]{typeof(global::System.String)});
        return (global::Sungero.Parties.IPerson)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{email});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.GetPersonByEmail(email);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::Sungero.Parties.ICompany GetCompanyByEmail(global::System.String email)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("GetCompanyByEmail", new global::System.Type[]{typeof(global::System.String)});
        return (global::Sungero.Parties.ICompany)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{email});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.GetCompanyByEmail(email);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::Sungero.Company.IBusinessUnit GetBusinessUnitByEmail(global::System.String email)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("GetBusinessUnitByEmail", new global::System.Type[]{typeof(global::System.String)});
        return (global::Sungero.Company.IBusinessUnit)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{email});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.GetBusinessUnitByEmail(email);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::System.Collections.Generic.List<global::System.String> GetListMail(global::System.String file)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("GetListMail", new global::System.Type[]{typeof(global::System.String)});
        return (global::System.Collections.Generic.List<global::System.String>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{file});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.GetListMail(file);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::System.Collections.Generic.List<global::System.String> GetListMailText(global::System.String file)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("GetListMailText", new global::System.Type[]{typeof(global::System.String)});
        return (global::System.Collections.Generic.List<global::System.String>)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{file});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.GetListMailText(file);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::System.Boolean DeleteDocumentVersions(global::Sungero.Content.IElectronicDocument document)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("DeleteDocumentVersions", new global::System.Type[]{typeof(global::Sungero.Content.IElectronicDocument)});
        return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{document});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.DeleteDocumentVersions(document);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    [global::Sungero.Core.RemoteAttribute()]
    internal static void ChangeDocumentsBody(global::Sungero.Docflow.IOfficialDocument firstDocument, global::Sungero.Docflow.IOfficialDocument secondDocument)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("ChangeDocumentsBody", new global::System.Type[]{typeof(global::Sungero.Docflow.IOfficialDocument), typeof(global::Sungero.Docflow.IOfficialDocument)});
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{firstDocument, secondDocument});
      }
      else
      {
    global::GD.DCSGovernmentModule.Server.ModuleFunctions.ChangeDocumentsBody(firstDocument, secondDocument);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static global::System.Boolean CopyDocumentBody(global::Sungero.Docflow.IOfficialDocument sourceDocument, global::Sungero.Docflow.IOfficialDocument receiverDocument)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("CopyDocumentBody", new global::System.Type[]{typeof(global::Sungero.Docflow.IOfficialDocument), typeof(global::Sungero.Docflow.IOfficialDocument)});
        return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{sourceDocument, receiverDocument});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.CopyDocumentBody(sourceDocument, receiverDocument);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static void CopyDocumentRelations(global::Sungero.Docflow.IOfficialDocument sourceDocument, global::Sungero.Docflow.IOfficialDocument receiverDocument)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("CopyDocumentRelations", new global::System.Type[]{typeof(global::Sungero.Docflow.IOfficialDocument), typeof(global::Sungero.Docflow.IOfficialDocument)});
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{sourceDocument, receiverDocument});
      }
      else
      {
    global::GD.DCSGovernmentModule.Server.ModuleFunctions.CopyDocumentRelations(sourceDocument, receiverDocument);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static void CopyDocumentSignatures(global::Sungero.Docflow.IOfficialDocument sourceDocument, global::Sungero.Docflow.IOfficialDocument receiverDocument)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("CopyDocumentSignatures", new global::System.Type[]{typeof(global::Sungero.Docflow.IOfficialDocument), typeof(global::Sungero.Docflow.IOfficialDocument)});
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{sourceDocument, receiverDocument});
      }
      else
      {
    global::GD.DCSGovernmentModule.Server.ModuleFunctions.CopyDocumentSignatures(sourceDocument, receiverDocument);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    internal static void MarkDocumentAsObsolete(global::Sungero.Docflow.IOfficialDocument document)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("MarkDocumentAsObsolete", new global::System.Type[]{typeof(global::Sungero.Docflow.IOfficialDocument)});
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{document});
      }
      else
      {
    global::GD.DCSGovernmentModule.Server.ModuleFunctions.MarkDocumentAsObsolete(document);
      }
    }
    /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ModuleFunctions" />
    [global::Sungero.Core.RemoteAttribute()]
    internal static global::System.Boolean ExistRegistrarForDocument(global::Sungero.Company.IBusinessUnit businessUnit, global::System.Boolean isRequest)
    {
      var __typeName = "GD.DCSGovernmentModule.Server.ModuleFunctions";
      var __type = global::Sungero.Metadata.Services.AppliedTypesManager.Instance.Resolve(__typeName);
      if (__type != null)
      {
        var __instance = global::Sungero.Metadata.Services.AppliedTypesManager.CreateTypeInstance(__type);
        var __methodInfo = __type.GetMethod("ExistRegistrarForDocument", new global::System.Type[]{typeof(global::Sungero.Company.IBusinessUnit), typeof(global::System.Boolean)});
        return (global::System.Boolean)global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__methodInfo, __instance, new object[]{businessUnit, isRequest});
      }
      else
      {
        return global::GD.DCSGovernmentModule.Server.ModuleFunctions.ExistRegistrarForDocument(businessUnit, isRequest);
      }
    }

    private static object GetFunctionsContainer()
    {
      return new global::GD.DCSGovernmentModule.Server.ModuleFunctions();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType, global::Sungero.Metadata.ModuleMetadata finalModuleMetadatda)
    {
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.FunctionNamespace, "Module", assemblyName));
      var methodInfo = moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static);
      return global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, null, null);
    }
  }
}

// ==================================================================
// ModuleInitializationInstantiation.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.ModuleInitialization
{
  internal static partial class Module
  {

    private static object GetFunctionsContainer()
    {
      return new global::GD.DCSGovernmentModule.Server.ModuleInitializer();
    }

    private static object GetFinalFunctionsContainer(global::Sungero.Metadata.ModuleProjectType projectType, global::Sungero.Metadata.ModuleMetadata finalModuleMetadatda)
    {
      var assemblyName = finalModuleMetadatda.GetAssemblyName(projectType);
      var moduleFunctionsType = global::System.Type.GetType(global::System.String.Format("{0}.{1}, {2}", finalModuleMetadatda.ModuleInitializationNamespace, "Module", assemblyName));
      var methodInfo = moduleFunctionsType.GetMethod("GetFunctionsContainer", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static);
      return global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(methodInfo, null, null);
    }

  }
}


// ==================================================================
// ModuleEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server
{
}

// ==================================================================
// ModuleServerPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server
{
  public partial class ModuleServerPublicFunctions : global::GD.DCSGovernmentModule.Server.IModuleServerPublicFunctions
  {
    public global::System.String CreateZipFromFile(global::System.String filePath)
    {
      return global::GD.DCSGovernmentModule.Functions.Module.CreateZipFromFile(filePath);
    }
    public global::Sungero.Company.IBusinessUnit GetBusinessUnitByEmail(global::System.String email)
    {
      return global::GD.DCSGovernmentModule.Functions.Module.GetBusinessUnitByEmail(email);
    }
    public global::Sungero.Parties.ICompany GetCompanyByEmail(global::System.String email)
    {
      return global::GD.DCSGovernmentModule.Functions.Module.GetCompanyByEmail(email);
    }
    public global::System.Collections.Generic.List<global::System.String> GetListMail(global::System.String file)
    {
      return global::GD.DCSGovernmentModule.Functions.Module.GetListMail(file);
    }
    public global::System.Collections.Generic.List<global::System.String> GetListMailText(global::System.String file)
    {
      return global::GD.DCSGovernmentModule.Functions.Module.GetListMailText(file);
    }
    public global::Sungero.Parties.IPerson GetPersonByEmail(global::System.String email)
    {
      return global::GD.DCSGovernmentModule.Functions.Module.GetPersonByEmail(email);
    }
  }
}

namespace GD.DCSGovernmentModule.Server
{
  public partial class ModuleServerPublicFunctions : global::GD.DCSGovernmentModule.Server.IModuleServerPublicFunctions
  {

      private static readonly global::System.Guid AsyncHandlerDeleteVersionsByDocumentIdId = global::System.Guid.Parse("8b517fb6-2e42-4f1a-bb8a-7f80134eb7bf");

      public void Enqueue_DeleteVersionsByDocumentId(global::Sungero.Domain.AsyncHandlerInvokeArgs args)
      {
         global:: Sungero.Metadata.AsyncHandlerDelayStrategy delayStrategy = global::Sungero.Metadata.AsyncHandlerDelayStrategy.RegularDelayStrategy;
           int delayInterval = 15;
 
         global::Sungero.Agent.Api.DelayStrategyInfo delayStrategyInfo = new global::Sungero.Agent.Api.DelayStrategyInfo(delayStrategy, delayInterval);
         global::Sungero.Agent.AsyncHandlersManager.Enqueue(AsyncHandlerDeleteVersionsByDocumentIdId, null, args, delayStrategyInfo);
      }
 
      private static readonly global::System.Guid AsyncHandlerCompleteAssignmentAsyncId = global::System.Guid.Parse("752c4084-6ed0-4519-96e9-cf7a804b5420");

      public void Enqueue_CompleteAssignmentAsync(global::Sungero.Domain.AsyncHandlerInvokeArgs args)
      {
         global:: Sungero.Metadata.AsyncHandlerDelayStrategy delayStrategy = global::Sungero.Metadata.AsyncHandlerDelayStrategy.RegularDelayStrategy;
           int delayInterval = 15;
 
         global::Sungero.Agent.Api.DelayStrategyInfo delayStrategyInfo = new global::Sungero.Agent.Api.DelayStrategyInfo(delayStrategy, delayInterval);
         global::Sungero.Agent.AsyncHandlersManager.Enqueue(AsyncHandlerCompleteAssignmentAsyncId, null, args, delayStrategyInfo);
      }
 

  }
}

// ==================================================================
// ModuleServerInitializationFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server
{
  public partial class ModuleServerInitializationFunctions : global::GD.DCSGovernmentModule.Server.IModuleServerInitializationFunctions
  {
  }
}


// ==================================================================
// ModuleWidgetHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server
{
}

// ==================================================================
// ModuleBlockHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server.DCSGovernmentModuleBlocks
{
}

namespace Sungero.Workflow
{
}

// ==================================================================
// ModuleQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Queries
{
  public class Module
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("GD.DCSGovernmentModule.Server.ModuleQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}

// ==================================================================
// ModuleInitializer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Server
{
  public partial class ModuleInitializer : global::Sungero.Domain.AppliedModuleInitializer
  {
  }
}

