
// ==================================================================
// ProcessingRuleRequest.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class ProcessingRuleRequest :
    global::GD.DCSGovernment.Client.ProcessingRuleDocBase, global::GD.DCSGovernmentModule.IProcessingRuleRequest
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("80051758-3f3f-4fcc-a772-f10c3c8e5bfd");

    public override global::System.Guid TypeGuid
    {
      get { return global::GD.DCSGovernmentModule.Client.ProcessingRuleRequest.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "GD.DCSGovernmentModule.IProcessingRuleRequest, Sungero.Domain.Interfaces"; }
    }

      public override string DisplayValue
      {
        get { return this.Name; }
        set { this.Name = value; }
      }

      public override string DisplayPropertyName
      {
        get { return "Name"; }
      }


    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestState State
    {
      get
      {
        return (global::GD.DCSGovernmentModule.IProcessingRuleRequestState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestState(this);
    }

    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestInfo Info
    {
      get
      {
        return (global::GD.DCSGovernmentModule.IProcessingRuleRequestInfo)base.Info;
      }
    }

    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestAccessRights AccessRights
    {
      get
      {
        return (global::GD.DCSGovernmentModule.IProcessingRuleRequestAccessRights)base.AccessRights;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestAccessRights(this);
    }

        protected global::Sungero.Domain.Client.SimpleProperty<global::System.String> _SubjectPattern;

        public virtual global::System.String SubjectPattern
        {
          get { return this._SubjectPattern.Value; }
          set { this._SubjectPattern.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?> _FillFromSubject;

        public virtual global::System.Boolean? FillFromSubject
        {
          get { return this._FillFromSubject.Value; }
          set { this._FillFromSubject.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?> _IsAutoCalcCorrespondent;

        public virtual global::System.Boolean? IsAutoCalcCorrespondent
        {
          get { return this._IsAutoCalcCorrespondent.Value; }
          set { this._IsAutoCalcCorrespondent.Value = value; }
        }
        protected global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?> _FillFromFileName;

        public virtual global::System.Boolean? FillFromFileName
        {
          get { return this._FillFromFileName.Value; }
          set { this._FillFromFileName.Value = value; }
        }




              protected global::Sungero.Domain.Client.INavigationProperty<global::Sungero.Parties.IPerson> _Correspondent;

              public virtual global::Sungero.Parties.IPerson Correspondent
              {
              get
              {
                return this._Correspondent.Value as global::Sungero.Parties.IPerson;
              }

              set
              {
                (this._Correspondent as global::Sungero.Domain.Client.IProperty).Value = value;
              }
            }



              protected global::Sungero.Domain.Client.INavigationProperty<global::Sungero.Company.IDepartment> _Department;

              public virtual global::Sungero.Company.IDepartment Department
              {
              get
              {
                return this._Department.Value as global::Sungero.Company.IDepartment;
              }

              set
              {
                (this._Department as global::Sungero.Domain.Client.IProperty).Value = value;
              }
            }










    #endregion

    #region Methods

    protected override object CreateActionsHandlers()
    {
      return new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestActions(this);
    }

    protected override object CreateCollectionActionsHandlers()
    {
      return new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestCollectionActions();
    }

    protected override object CreateAnyChildEntityActionsHandlers()
    {
      return new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestAnyChildEntityActions();
    }

    protected override object CreateAnyChildEntityCollectionActionsHandlers()
    {
      return new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestAnyChildEntityCollectionActions();
    }


    protected override global::Sungero.Domain.Client.EntityFunctions CreateClientFunctions()
    {
      return new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestFunctions(this);
    }
    protected override object CreateHandlers() {
      return new global::GD.DCSGovernmentModule.ProcessingRuleRequestClientHandlers(this);
    }
    protected override object CreateSharedHandlers() {
      return new global::GD.DCSGovernmentModule.ProcessingRuleRequestSharedHandlers(this);
    }

    #endregion

    #region Framework events

    protected void SubjectPatternChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.StringPropertyChangedEventArgs(this.State.Properties.SubjectPattern, this.SubjectPattern, this);
     ((global::GD.DCSGovernmentModule.IProcessingRuleRequestSharedHandlers)this.SharedHandlers).SubjectPatternChanged(args);
    }

    protected void FillFromSubjectChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs(this.State.Properties.FillFromSubject, this.FillFromSubject, this);
     ((global::GD.DCSGovernmentModule.IProcessingRuleRequestSharedHandlers)this.SharedHandlers).FillFromSubjectChanged(args);
    }

    protected void CorrespondentChangedHandler()
    {
      var args = new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestCorrespondentChangedEventArgs(this.State.Properties.Correspondent, this.Correspondent, this);
     ((global::GD.DCSGovernmentModule.IProcessingRuleRequestSharedHandlers)this.SharedHandlers).CorrespondentChanged(args);
    }

    protected void IsAutoCalcCorrespondentChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs(this.State.Properties.IsAutoCalcCorrespondent, this.IsAutoCalcCorrespondent, this);
     ((global::GD.DCSGovernmentModule.IProcessingRuleRequestSharedHandlers)this.SharedHandlers).IsAutoCalcCorrespondentChanged(args);
    }

    protected void DepartmentChangedHandler()
    {
      var args = new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestDepartmentChangedEventArgs(this.State.Properties.Department, this.Department, this);
     ((global::GD.DCSGovernmentModule.IProcessingRuleRequestSharedHandlers)this.SharedHandlers).DepartmentChanged(args);
    }

    protected void FillFromFileNameChangedHandler()
    {
      var args = new global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs(this.State.Properties.FillFromFileName, this.FillFromFileName, this);
     ((global::GD.DCSGovernmentModule.IProcessingRuleRequestSharedHandlers)this.SharedHandlers).FillFromFileNameChanged(args);
    }




  protected global::System.String SubjectPatternValueInputHandler(global::System.String value)
  {
    var args = new global::Sungero.Presentation.StringValueInputEventArgs(this.SubjectPattern, value, this, this.Info.Properties.SubjectPattern);
    ((global::GD.DCSGovernmentModule.ProcessingRuleRequestClientHandlers)this.Handlers).SubjectPatternValueInput(args);
    return args.NewValue;
  }

  protected global::System.Boolean? FillFromSubjectValueInputHandler(global::System.Boolean? value)
  {
    var args = new global::Sungero.Presentation.BooleanValueInputEventArgs(this.FillFromSubject, value, this, this.Info.Properties.FillFromSubject);
    ((global::GD.DCSGovernmentModule.ProcessingRuleRequestClientHandlers)this.Handlers).FillFromSubjectValueInput(args);
    return args.NewValue;
  }

  protected global::Sungero.Parties.IPerson CorrespondentValueInputHandler(global::Sungero.Parties.IPerson value)
  {
    var args = new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestCorrespondentValueInputEventArgs(this.Correspondent, value, this, this.Info.Properties.Correspondent);
    ((global::GD.DCSGovernmentModule.ProcessingRuleRequestClientHandlers)this.Handlers).CorrespondentValueInput(args);
    return args.NewValue;
  }

  protected global::System.Boolean? IsAutoCalcCorrespondentValueInputHandler(global::System.Boolean? value)
  {
    var args = new global::Sungero.Presentation.BooleanValueInputEventArgs(this.IsAutoCalcCorrespondent, value, this, this.Info.Properties.IsAutoCalcCorrespondent);
    ((global::GD.DCSGovernmentModule.ProcessingRuleRequestClientHandlers)this.Handlers).IsAutoCalcCorrespondentValueInput(args);
    return args.NewValue;
  }

  protected global::Sungero.Company.IDepartment DepartmentValueInputHandler(global::Sungero.Company.IDepartment value)
  {
    var args = new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestDepartmentValueInputEventArgs(this.Department, value, this, this.Info.Properties.Department);
    ((global::GD.DCSGovernmentModule.ProcessingRuleRequestClientHandlers)this.Handlers).DepartmentValueInput(args);
    return args.NewValue;
  }

  protected global::System.Boolean? FillFromFileNameValueInputHandler(global::System.Boolean? value)
  {
    var args = new global::Sungero.Presentation.BooleanValueInputEventArgs(this.FillFromFileName, value, this, this.Info.Properties.FillFromFileName);
    ((global::GD.DCSGovernmentModule.ProcessingRuleRequestClientHandlers)this.Handlers).FillFromFileNameValueInput(args);
    return args.NewValue;
  }



    #endregion

    #region Constructors





              protected virtual void InitCorrespondentNavigationProperty()
              {
                this._Correspondent = new global::Sungero.Domain.Client.NavigationProperty<global::Sungero.Parties.IPerson>("Correspondent", this);
                this._Correspondent.ValueChanged += (sender, e) => { this.CorrespondentChangedHandler(); };
                this.AddProperty(this._Correspondent as global::Sungero.Domain.Client.IProperty);
              }




              protected virtual void InitDepartmentNavigationProperty()
              {
                this._Department = new global::Sungero.Domain.Client.NavigationProperty<global::Sungero.Company.IDepartment>("Department", this);
                this._Department.ValueChanged += (sender, e) => { this.DepartmentChangedHandler(); };
                this.AddProperty(this._Department as global::Sungero.Domain.Client.IProperty);
              }



            protected override void InitPerformersCollectionProperty()
            {
              this._Performers = new global::Sungero.Domain.Client.ListProperty<global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers>("Performers", this);
              this._Performers.ValueChanged += (sender, e) => { this.PerformersChangedHandler(); };
              this.AddProperty((global::Sungero.Domain.Client.IProperty)this._Performers);
              this.SetPerformersEventHandlers();
            }


    public ProcessingRuleRequest()
    {
            this._SubjectPattern = new global::Sungero.Domain.Client.SimpleProperty<global::System.String>("SubjectPattern", this);
            this._SubjectPattern.ValueChanged += (sender, e) => { this.SubjectPatternChangedHandler(); };
            this.AddProperty(this._SubjectPattern);

            this._FillFromSubject = new global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?>("FillFromSubject", this);
            this._FillFromSubject.ValueChanged += (sender, e) => { this.FillFromSubjectChangedHandler(); };
            this.AddProperty(this._FillFromSubject);

            this._IsAutoCalcCorrespondent = new global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?>("IsAutoCalcCorrespondent", this);
            this._IsAutoCalcCorrespondent.ValueChanged += (sender, e) => { this.IsAutoCalcCorrespondentChangedHandler(); };
            this.AddProperty(this._IsAutoCalcCorrespondent);

            this._FillFromFileName = new global::Sungero.Domain.Client.SimpleProperty<global::System.Boolean?>("FillFromFileName", this);
            this._FillFromFileName.ValueChanged += (sender, e) => { this.FillFromFileNameChangedHandler(); };
            this.AddProperty(this._FillFromFileName);

            this.InitCorrespondentNavigationProperty();

            this.InitDepartmentNavigationProperty();








    }

    #endregion

  }
}

// ==================================================================
// ProcessingRuleRequestPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class ProcessingRuleRequestPresenter<T> :
    global::GD.DCSGovernment.Client.ProcessingRuleDocBasePresenter<T>
    where T : class, global::GD.DCSGovernmentModule.IProcessingRuleRequest
  {
    #region Fields and properties




    #endregion

    #region Methods


    #endregion

    #region Framework events

    protected override void EntityPropertyChangedEventHandler(object sender, global::System.ComponentModel.PropertyChangedEventArgs e)
    {
      base.EntityPropertyChangedEventHandler(sender, e);
    }

    #endregion

              protected global::Sungero.Domain.Client.IEntityCollectionPresenter _CorrespondentCollectionPresenter;
              public global::Sungero.Domain.Client.IEntityCollectionPresenter CorrespondentCollectionPresenter
              {
          get { return this._CorrespondentCollectionPresenter; }
        }
              protected global::Sungero.Domain.Client.IEntityCollectionPresenter _DepartmentCollectionPresenter;
              public global::Sungero.Domain.Client.IEntityCollectionPresenter DepartmentCollectionPresenter
              {
          get { return this._DepartmentCollectionPresenter; }
        }



    #region Constructors

    private void Init()
    {
              this._ApprovalRuleCollectionPresenter
              .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationProperty<global::Sungero.Docflow.IApprovalRuleBase>(() => this.Entity, typeof(T), "ApprovalRule");

              this._DocumentKindCollectionPresenter
              .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationProperty<global::Sungero.Docflow.IDocumentKind>(() => this.Entity, typeof(T), "DocumentKind");

                  this._CorrespondentCollectionPresenter = this.CreateCollectionPresenterForNavigationProperty<global::Sungero.Parties.IPerson>(global::System.Guid.Parse("f8c7da80-d32d-4b00-a3af-eb1f6ca21634"));
              this._CorrespondentCollectionPresenter
              .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationPropertyWithoutSourceEntity<global::Sungero.Parties.IPerson>(() => this.Entity.Id, typeof(T), "Correspondent");

                  this._DepartmentCollectionPresenter = this.CreateCollectionPresenterForNavigationProperty<global::Sungero.Company.IDepartment>(global::System.Guid.Parse("1c60f245-e55e-40a2-8332-9af3ae97d376"));
              this._DepartmentCollectionPresenter
              .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationPropertyWithoutSourceEntity<global::Sungero.Company.IDepartment>(() => this.Entity.Id, typeof(T), "Department");


                        this._PerformersPerformerCollectionPresenter
                        .Query = global::Sungero.Domain.Client.Session.GetValuesForNavigationPropertyWithoutSourceEntity<global::Sungero.Company.IEmployee>(() => this.Entity.Id, typeof(GD.DCSGovernmentModule.IProcessingRuleRequestPerformers), "Performer");



    }

    public ProcessingRuleRequestPresenter()
    {
      this.Init();
    }

    #endregion
  }
}

// ==================================================================
// ProcessingRuleRequestCollectionPresenter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class ProcessingRuleRequestCollectionPresenter<T> : 
    global::GD.DCSGovernment.Client.ProcessingRuleDocBaseCollectionPresenter<T>
    where T: class, global::GD.DCSGovernmentModule.IProcessingRuleRequest
  {
    #region Actions



    #endregion

    #region Methods


    #endregion

    public ProcessingRuleRequestCollectionPresenter(global::System.Linq.IQueryable<T> query, OnLookup onLookup)
      : base(query, onLookup)
    {
    }

    public ProcessingRuleRequestCollectionPresenter(global::System.Linq.IQueryable<T> query)
      : this(query, null) { }

    public ProcessingRuleRequestCollectionPresenter(OnLookup onLookup)
      : this(null, onLookup) { }

    public ProcessingRuleRequestCollectionPresenter()
      : this(null, null) { }
  }
}

// ==================================================================
// ProcessingRuleRequestRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{ 
  public class ProcessingRuleRequestRepositoryImplementer<T> : 
      global::GD.DCSGovernment.Client.ProcessingRuleDocBaseRepositoryImplementer<T>,
      global::GD.DCSGovernmentModule.IProcessingRuleRequestRepositoryImplementer<T>
      where T : global::GD.DCSGovernmentModule.IProcessingRuleRequest
    {
       public new global::GD.DCSGovernmentModule.IProcessingRuleRequestAccessRights AccessRights
       {
          get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestAccessRights)base.AccessRights; }
       }

       public new global::GD.DCSGovernmentModule.IProcessingRuleRequestInfo Info
       {
          get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// ProcessingRuleRequestAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class ProcessingRuleRequestAccessRights : 
    GD.DCSGovernment.Client.ProcessingRuleDocBaseAccessRights, GD.DCSGovernmentModule.IProcessingRuleRequestAccessRights
  {

    public ProcessingRuleRequestAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class ProcessingRuleRequestTypeAccessRights : 
    GD.DCSGovernment.Client.ProcessingRuleDocBaseTypeAccessRights, GD.DCSGovernmentModule.IProcessingRuleRequestAccessRights
  {

    public ProcessingRuleRequestTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}
