//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  /// <summary>
  /// Interaction logic for ProcessingRuleRequestCollectionView.xaml.
  /// </summary>
  public partial class ProcessingRuleRequestCollectionView : global::System.Windows.Controls.UserControl
  {
    public ProcessingRuleRequestCollectionView()
    {
      InitializeComponent();
    }
  }
}