
// ==================================================================
// ProcessingRuleRequestState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class ProcessingRuleRequestState : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBaseState, global::GD.DCSGovernmentModule.IProcessingRuleRequestState
  {
    public ProcessingRuleRequestState(global::GD.DCSGovernmentModule.IProcessingRuleRequest entity) : base(entity) { }

    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestPropertyStates Properties
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPropertyStates(entity);
    }


    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestControlStates Controls
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestControlStates)base.Controls; }
    }

    protected override global::Sungero.Domain.Shared.IEntityControlStates CreateControlStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestControlStates(entity);
    }

    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestPageStates Pages
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestPageStates)base.Pages; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPageStates CreatePageStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPageStates(entity);
    }

  }


  public class ProcessingRuleRequestControlStates : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBaseControlStates, global::GD.DCSGovernmentModule.IProcessingRuleRequestControlStates
  {

    protected internal ProcessingRuleRequestControlStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }
  public class ProcessingRuleRequestPageStates : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePageStates, global::GD.DCSGovernmentModule.IProcessingRuleRequestPageStates
  {

    protected internal ProcessingRuleRequestPageStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class ProcessingRuleRequestPropertyStates : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePropertyStates, global::GD.DCSGovernmentModule.IProcessingRuleRequestPropertyStates
  {
            public new global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersCollectionPropertyState<global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers> Performers
            {
              get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersCollectionPropertyState<global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers>)base.Performers; }
            }

            protected override global::DirRX.DCTSIntegration.IProcessingRuleBasePerformersCollectionPropertyState<global::DirRX.DCTSIntegration.IProcessingRuleBasePerformers> CreatePerformersState(global::Sungero.Domain.Shared.IEntity entity, string propertyName)
            {
              return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPerformersCollectionPropertyState<global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers>(entity, propertyName);
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.String> SubjectPattern 
            {
              get { return this.GetPropertyState<global::System.String>("SubjectPattern"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Boolean?> FillFromSubject 
            {
              get { return this.GetPropertyState<global::System.Boolean?>("FillFromSubject"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Parties.IPerson> Correspondent 
            {
              get { return this.InternalCorrespondent; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Parties.IPerson> InternalCorrespondent
            {
              get { return this.GetPropertyState<global::Sungero.Parties.IPerson>("Correspondent"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Boolean?> IsAutoCalcCorrespondent 
            {
              get { return this.GetPropertyState<global::System.Boolean?>("IsAutoCalcCorrespondent"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IDepartment> Department 
            {
              get { return this.InternalDepartment; }
            }

            protected virtual global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Company.IDepartment> InternalDepartment
            {
              get { return this.GetPropertyState<global::Sungero.Company.IDepartment>("Department"); }
            }
            public global::Sungero.Domain.Shared.IPropertyState<global::System.Boolean?> FillFromFileName 
            {
              get { return this.GetPropertyState<global::System.Boolean?>("FillFromFileName"); }
            }


    protected internal ProcessingRuleRequestPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

}

// ==================================================================
// ProcessingRuleRequestInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class ProcessingRuleRequestInfo : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBaseInfo, global::GD.DCSGovernmentModule.IProcessingRuleRequestInfo
  {
    public ProcessingRuleRequestInfo(global::System.Type entityType) : base(entityType) { }

    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestPropertiesInfo Properties
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPropertiesInfo(entityType);
    }

  }

  public class ProcessingRuleRequestPropertiesInfo : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePropertiesInfo, global::GD.DCSGovernmentModule.IProcessingRuleRequestPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.ICollectionPropertyInfo<global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertiesInfo> Performers
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.CollectionPropertyMetadata>("Performers");
             return new global::Sungero.Domain.Shared.CollectionPropertyInfo<global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertiesInfo>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IStringPropertyInfo SubjectPattern 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.StringPropertyMetadata>("SubjectPattern");
             return new global::Sungero.Domain.Shared.StringPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IBooleanPropertyInfo FillFromSubject 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.BooleanPropertyMetadata>("FillFromSubject");
             return new global::Sungero.Domain.Shared.BooleanPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Parties.IPersonInfo, global::Sungero.Parties.IPerson> Correspondent 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Correspondent");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Parties.IPersonInfo, global::Sungero.Parties.IPerson>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IBooleanPropertyInfo IsAutoCalcCorrespondent 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.BooleanPropertyMetadata>("IsAutoCalcCorrespondent");
             return new global::Sungero.Domain.Shared.BooleanPropertyInfo(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.INavigationPropertyInfo<global::Sungero.Company.IDepartmentInfo, global::Sungero.Company.IDepartment> Department 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Department");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::Sungero.Company.IDepartmentInfo, global::Sungero.Company.IDepartment>(propertyMetadata);
          }
        }
        public global::Sungero.Domain.Shared.IBooleanPropertyInfo FillFromFileName 
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.BooleanPropertyMetadata>("FillFromFileName");
             return new global::Sungero.Domain.Shared.BooleanPropertyInfo(propertyMetadata);
          }
        }


    protected internal ProcessingRuleRequestPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}

// ==================================================================
// ProcessingRuleRequestHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule
{
  public partial class ProcessingRuleRequestSharedHandlers : global::GD.DCSGovernment.ProcessingRuleDocBaseSharedHandlers, IProcessingRuleRequestSharedHandlers
  {
    private global::GD.DCSGovernmentModule.IProcessingRuleRequest _obj
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequest)this.Entity; }
    }
    public virtual void SubjectPatternChanged(global::Sungero.Domain.Shared.StringPropertyChangedEventArgs e) { }



    public virtual void CorrespondentChanged(global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestCorrespondentChangedEventArgs e) { }


    public virtual void IsAutoCalcCorrespondentChanged(global::Sungero.Domain.Shared.BooleanPropertyChangedEventArgs e) { }


    public virtual void DepartmentChanged(global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestDepartmentChangedEventArgs e) { }





    public ProcessingRuleRequestSharedHandlers(global::GD.DCSGovernmentModule.IProcessingRuleRequest entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// ProcessingRuleRequestResources.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared.ProcessingRuleRequest
{
  /// <summary>
  /// Represents ProcessingRuleRequest resources.
  /// </summary>
  public class ProcessingRuleRequestResources : global::GD.DCSGovernment.Shared.ProcessingRuleDocBase.ProcessingRuleDocBaseResources, global::GD.DCSGovernmentModule.ProcessingRuleRequest.IProcessingRuleRequestResources
  {
    public virtual global::CommonLibrary.LocalizedString BusinessUnitUnfilled
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IProcessingRuleRequest) , "BusinessUnitUnfilled");
      }
    }

    public virtual global::CommonLibrary.LocalizedString BusinessUnitUnfilledFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IProcessingRuleRequest), "BusinessUnitUnfilled", false, args);
    }
    public virtual global::CommonLibrary.LocalizedString RequiredSubjectPattern
    {
      get
      {
        return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IProcessingRuleRequest) , "RequiredSubjectPattern");
      }
    }

    public virtual global::CommonLibrary.LocalizedString RequiredSubjectPatternFormat(params object[] args)
    {
      return global::Sungero.Domain.Shared.ResourceService.Instance.GetEntityStringResource(typeof(GD.DCSGovernmentModule.IProcessingRuleRequest), "RequiredSubjectPattern", false, args);
    }

  }
}

// ==================================================================
// ProcessingRuleRequestSharedFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Shared
{
  public partial class ProcessingRuleRequestFunctions : global::GD.DCSGovernment.Shared.ProcessingRuleDocBaseFunctions
  {
    private global::GD.DCSGovernmentModule.IProcessingRuleRequest _obj
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequest)this.Entity; }
    }

    public ProcessingRuleRequestFunctions(global::GD.DCSGovernmentModule.IProcessingRuleRequest entity) : base(entity) { }
  }
}

// ==================================================================
// ProcessingRuleRequestFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Functions
{
  internal static class ProcessingRuleRequest
  {
    /// <redirect project="GD.DCSGovernmentModule.Shared" type="GD.DCSGovernmentModule.Shared.ProcessingRuleRequestFunctions" />
    internal static  void SetPropertiesVisibility(global::GD.DCSGovernmentModule.IProcessingRuleRequest processingRuleRequest)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)processingRuleRequest).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetPropertiesVisibility", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }
    /// <redirect project="GD.DCSGovernmentModule.Shared" type="GD.DCSGovernmentModule.Shared.ProcessingRuleRequestFunctions" />
    internal static  void SetPropertiesAvailability(global::GD.DCSGovernmentModule.IProcessingRuleRequest processingRuleRequest)
    {
      var __functions = ((global::Sungero.Domain.Shared.IEntityFunctions)processingRuleRequest).FunctionsContainer.SharedFunctions;
      var __funcMethod = __functions.GetType().GetMethod("SetPropertiesAvailability", new System.Type[] {  });
    global::CommonLibrary.ReflectionExtensions.ReflectionInvoke(__funcMethod, __functions, new object[] {  });
    }

    internal static class Remote
    {
      /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ProcessingRuleRequestFunctions" />
      internal static  global::GD.DCSGovernmentModule.IProcessingRuleRequest GetProcessingRule(global::System.Int64 id)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::GD.DCSGovernmentModule.IProcessingRuleRequest>(
          global::System.Guid.Parse("80051758-3f3f-4fcc-a772-f10c3c8e5bfd"),
          "GetProcessingRule(global::System.Int64)"
      , id);
      }
      /// <redirect project="GD.DCSGovernmentModule.Server" type="GD.DCSGovernmentModule.Server.ProcessingRuleRequestFunctions" />
      internal static  global::Sungero.Docflow.IOfficialDocument CreateDocument(global::GD.DCSGovernmentModule.IProcessingRuleRequest processingRuleRequest)
      {
        return global::Sungero.Domain.Shared.RemoteFunctionExecutor.ExecuteWithResult<global::Sungero.Docflow.IOfficialDocument>(
          global::System.Guid.Parse("80051758-3f3f-4fcc-a772-f10c3c8e5bfd"),
          "CreateDocument(global::GD.DCSGovernmentModule.IProcessingRuleRequest)"
          , processingRuleRequest);
      }

    }
  }
}

// ==================================================================
// ProcessingRuleRequestFilterState.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Shared.ProcessingRuleRequest
{

  public class ProcessingRuleRequestFilterInfo : global::GD.DCSGovernment.Shared.ProcessingRuleDocBase.ProcessingRuleDocBaseFilterInfo,
    global::GD.DCSGovernmentModule.IProcessingRuleRequestFilterInfo
  {
  }

  public class ProcessingRuleRequestFilterState : global::GD.DCSGovernment.Shared.ProcessingRuleDocBase.ProcessingRuleDocBaseFilterState,
    global::GD.DCSGovernmentModule.IProcessingRuleRequestFilterState
  {



    public new GD.DCSGovernmentModule.IProcessingRuleRequestFilterInfo Info
    {
      get
      {
        return (GD.DCSGovernmentModule.IProcessingRuleRequestFilterInfo) base.Info;
      }
    }
    protected override global::Sungero.Domain.Shared.IFilterInfo CreateFilterInfo()
    {
      return new GD.DCSGovernmentModule.Shared.ProcessingRuleRequest.ProcessingRuleRequestFilterInfo();
    }

  }
}

// ==================================================================
// ProcessingRuleRequestSharedPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class ProcessingRuleRequestSharedPublicFunctions : global::GD.DCSGovernmentModule.Shared.IProcessingRuleRequestSharedPublicFunctions
  {
  }
}
