
// ==================================================================
// ProcessingRuleDocBasePerformers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{


  public class ProcessingRuleDocBasePerformers :
    global::DirRX.DCTSIntegration.Server.ProcessingRuleDocBasePerformers, global::GD.DCSGovernment.IProcessingRuleDocBasePerformers
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("ba791439-7977-48fc-8e2a-58341ffde32e");

    public override global::System.Guid TypeGuid
    {
      get { return global::GD.DCSGovernment.Server.ProcessingRuleDocBasePerformers.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "GD.DCSGovernment.IProcessingRuleDocBasePerformers, Sungero.Domain.Interfaces"; }
    }

    public new virtual global::GD.DCSGovernment.IProcessingRuleDocBasePerformersState State
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleDocBasePerformersState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersState(this);
    }

    public new virtual global::GD.DCSGovernment.IProcessingRuleDocBasePerformersInfo Info
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleDocBasePerformersInfo)base.Info; }
    }










    #region Framework events



    #endregion


    public ProcessingRuleDocBasePerformers()
    {
    }

  }
}

// ==================================================================
// ProcessingRuleDocBasePerformersHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment
{

}

// ==================================================================
// ProcessingRuleDocBasePerformersEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{
}
