
// ==================================================================
// ProcessingRuleRequestPerformersState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class ProcessingRuleRequestPerformersState : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersState, global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersState
  {
    public ProcessingRuleRequestPerformersState(global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers entity) : base(entity) { }

    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertyStates Properties
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPerformersPropertyStates(entity);
    }


  }


  public class ProcessingRuleRequestPerformersPropertyStates : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersPropertyStates, global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertyStates
  {
            public new global::Sungero.Domain.Shared.IPropertyState<global::GD.DCSGovernmentModule.IProcessingRuleRequest> ProcessingRuleBase
            {
              get { return (global::Sungero.Domain.Shared.IPropertyState<global::GD.DCSGovernmentModule.IProcessingRuleRequest>)base.ProcessingRuleBase; }
            }

            protected override global::Sungero.Domain.Shared.IPropertyState<global::DirRX.DCTSIntegration.IProcessingRuleBase> InternalProcessingRuleBase
            {
              get { return this.GetPropertyState<global::GD.DCSGovernmentModule.IProcessingRuleRequest>("ProcessingRuleBase"); }
            }


    protected internal ProcessingRuleRequestPerformersPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class ProcessingRuleRequestPerformersCollectionPropertyState<T> :
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersCollectionPropertyState<T>, global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersCollectionPropertyState<T>
    where T : global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers
  {
    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersCollectionPropertyStates Properties
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPerformersCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal ProcessingRuleRequestPerformersCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class ProcessingRuleRequestPerformersCollectionPropertyStates :
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersCollectionPropertyStates, global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersCollectionPropertyStates
  {

    protected internal ProcessingRuleRequestPerformersCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// ProcessingRuleRequestPerformersInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class ProcessingRuleRequestPerformersInfo : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersInfo, global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersInfo
  {
    public ProcessingRuleRequestPerformersInfo(global::System.Type entityType) : base(entityType) { }

    public new global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertiesInfo Properties
    {
      get { return (global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPerformersPropertiesInfo(entityType);
    }

  }

  public class ProcessingRuleRequestPerformersPropertiesInfo : 
    global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersPropertiesInfo, global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformersPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.INavigationPropertyInfo<global::GD.DCSGovernmentModule.IProcessingRuleRequestInfo, global::GD.DCSGovernmentModule.IProcessingRuleRequest> ProcessingRuleBase
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("ProcessingRuleBase");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::GD.DCSGovernmentModule.IProcessingRuleRequestInfo, global::GD.DCSGovernmentModule.IProcessingRuleRequest>(propertyMetadata);
          }
        }


    protected internal ProcessingRuleRequestPerformersPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
