
// ==================================================================
// RegistrationAssignmentEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{ 
  public class RegistrationAssignmentRegistrarValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Company.IEmployee>
  {
    public RegistrationAssignmentRegistrarValueInputEventArgs(global::Sungero.Company.IEmployee oldValue, global::Sungero.Company.IEmployee newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

  public class RegistrationAssignmentBusinessUnitValueInputEventArgs : global::Sungero.Presentation.ValueInputEventArgs<global::Sungero.Company.IBusinessUnit>
  {
    public RegistrationAssignmentBusinessUnitValueInputEventArgs(global::Sungero.Company.IBusinessUnit oldValue, global::Sungero.Company.IBusinessUnit newValue, global::Sungero.Domain.Shared.IEntity entity, global::Sungero.Domain.Shared.IPropertyInfo propertyInfo): base(oldValue, newValue, entity, propertyInfo) { }
  }

}

// ==================================================================
// RegistrationAssignmentHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule
{

  public partial class RegistrationAssignmentFilteringClientHandler
    : global::Sungero.Domain.EntityFilteringClientHandler
  {
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    protected global::GD.DCSGovernmentModule.IRegistrationAssignmentFilterState Filter { get; private set; }

    private global::GD.DCSGovernmentModule.IRegistrationAssignmentFilterState _filter
    {
      get
      {
        return this.Filter;
      }
    }

    public RegistrationAssignmentFilteringClientHandler(global::GD.DCSGovernmentModule.IRegistrationAssignmentFilterState filter)
    : base()
    {
      this.Filter = filter;
    }

    protected RegistrationAssignmentFilteringClientHandler()
    {
    }

    public override void ValidateFilterPanel(global::Sungero.Domain.Client.ValidateFilterPanelEventArgs e)
    {
    }
  }


  public partial class RegistrationAssignmentClientHandlers : global::Sungero.Workflow.AssignmentClientHandlers
  {
    private global::GD.DCSGovernmentModule.IRegistrationAssignment _obj
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignment)this.Entity; }
    }

    public virtual void RegistrarValueInput(global::GD.DCSGovernmentModule.Client.RegistrationAssignmentRegistrarValueInputEventArgs e) { }


    public virtual void BusinessUnitValueInput(global::GD.DCSGovernmentModule.Client.RegistrationAssignmentBusinessUnitValueInputEventArgs e) { }


    public RegistrationAssignmentClientHandlers(global::GD.DCSGovernmentModule.IRegistrationAssignment entity) : base(entity)
    {
    }
  }

}

// ==================================================================
// RegistrationAssignmentClientFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernmentModule.Client
{
  public partial class RegistrationAssignmentFunctions : global::Sungero.Workflow.Client.AssignmentFunctions
  {
    private global::GD.DCSGovernmentModule.IRegistrationAssignment _obj
    {
      get { return (global::GD.DCSGovernmentModule.IRegistrationAssignment)this.Entity; }
    }

    public RegistrationAssignmentFunctions(global::GD.DCSGovernmentModule.IRegistrationAssignment entity) : base(entity) { }
  }
}

// ==================================================================
// RegistrationAssignmentFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Functions
{
  internal static class RegistrationAssignment
  {
  }
}

// ==================================================================
// RegistrationAssignmentClientPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public class RegistrationAssignmentClientPublicFunctions : global::GD.DCSGovernmentModule.Client.IRegistrationAssignmentClientPublicFunctions
  {
  }
}

// ==================================================================
// RegistrationAssignmentActions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public partial class RegistrationAssignmentActions : global::Sungero.Workflow.Client.AssignmentActions
  {
    private global::GD.DCSGovernmentModule.IRegistrationAssignment _obj { get { return (global::GD.DCSGovernmentModule.IRegistrationAssignment)this.Entity; } }
    public RegistrationAssignmentActions(global::GD.DCSGovernmentModule.IRegistrationAssignment entity) : base(entity) { }
  }

  public partial class RegistrationAssignmentCollectionActions : global::Sungero.Workflow.Client.AssignmentCollectionActions
  {
    private global::System.Collections.Generic.IEnumerable<global::GD.DCSGovernmentModule.IRegistrationAssignment> _objs
    {
      get { return global::System.Linq.Enumerable.Cast<global::GD.DCSGovernmentModule.IRegistrationAssignment>(this.Entities); }
    }
  }

  public partial class RegistrationAssignmentCollectionBulkActions : global::Sungero.Workflow.Client.AssignmentCollectionBulkActions
  {
    private global::System.Collections.Generic.IEnumerable<global::System.Int64> _objIds
    {
      get { return this.EntityIds; }
    }
  }


  public partial class RegistrationAssignmentAnyChildEntityActions : global::Sungero.Workflow.Client.AssignmentAnyChildEntityActions
  {
  }

  public partial class RegistrationAssignmentAnyChildEntityCollectionActions : global::Sungero.Workflow.Client.AssignmentAnyChildEntityCollectionActions
  {
  }



}
