//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{
  /// <summary>
  /// Interaction logic for ProcessingRuleIncomingLetterCollectionView.xaml.
  /// </summary>
  public partial class ProcessingRuleIncomingLetterCollectionView : global::System.Windows.Controls.UserControl
  {
    public ProcessingRuleIncomingLetterCollectionView()
    {
      InitializeComponent();
    }
  }
}