
// ==================================================================
// ProcessingRuleIncomingLetter.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{
    public class ProcessingRuleIncomingLetterFilter<T> :
      global::DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterFilter<T>
      where T : class, global::GD.DCSGovernment.IProcessingRuleIncomingLetter
    {
      private global::GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState filter
      {
        get
        {
          return (GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState)this.Filter;
        }
      }

      protected override global::System.Linq.IQueryable<T> ApplyAppliedFilter(global::System.Linq.IQueryable<T> query)
      {
        return base.ApplyAppliedFilter(query);
      }

      public ProcessingRuleIncomingLetterFilter(global::GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState filter)
      : base(filter)
      {
      }

      protected ProcessingRuleIncomingLetterFilter()
      {
      }
    }
      public class ProcessingRuleIncomingLetterUiFilter<T> :
        global::DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterUiFilter<T>
        where T : class, global::GD.DCSGovernment.IProcessingRuleIncomingLetter
      {
        protected override global::System.Linq.IQueryable<T> ApplyAppliedFilter(global::System.Linq.IQueryable<T> query)
        {
          return base.ApplyAppliedFilter(query);
        }
      }

    public class ProcessingRuleIncomingLetterSearchDialogModel : global::DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterSearchDialogModel
        {
                  public override global::System.Int64? Id { get; protected set; }
                  public override global::System.String Name { get; protected set; }
                  public override global::System.String Note { get; protected set; }
                  public override global::System.String Line { get; protected set; }
                  public override global::System.String NamePattern { get; protected set; }
                  public override global::System.Int32? DeadlineInDays { get; protected set; }
                  public override global::System.Int32? DeadlineInHours { get; protected set; }
                  public override global::System.String TaskSubject { get; protected set; }
                  public override global::System.String SubjectPattern { get; protected set; }


                  public override global::System.Collections.Generic.IEnumerable<Sungero.Docflow.IApprovalRuleBase> ApprovalRule { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Core.Enumeration> TaskType { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Docflow.IDocumentKind> DocumentKind { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Core.Enumeration> CaptureService { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Core.Enumeration> Status { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Parties.ICounterparty> Correspondent { get; protected set; }
                  public override global::System.Collections.Generic.IEnumerable<Sungero.Company.IDepartment> Department { get; protected set; }




                   [Sungero.Domain.Shared.HideInDevStudio()]
                   public new ProcessingRuleIncomingLetterPerformersModel Performers { get { return (ProcessingRuleIncomingLetterPerformersModel)base.Performers; } protected set { base.Performers = value; } }

        }

      public class ProcessingRuleIncomingLetterPerformersModel : global::DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterPerformersModel
          {
                      [Sungero.Domain.Shared.HideInDevStudio()]
                      public override global::System.Int64? Id { get; protected set; }




         }





  [global::Sungero.Domain.Filter(typeof(global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterFilter<global::GD.DCSGovernment.IProcessingRuleIncomingLetter>))]
  [global::Sungero.Domain.UiFilter(typeof(global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterUiFilter<global::GD.DCSGovernment.IProcessingRuleIncomingLetter>))]

  public class ProcessingRuleIncomingLetter :
    global::DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetter, global::GD.DCSGovernment.IProcessingRuleIncomingLetter
  {
    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("d0432c80-f060-494d-89dc-bfb89a1d828f");

    public override global::System.Guid TypeGuid
    {
      get { return global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetter.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "GD.DCSGovernment.IProcessingRuleIncomingLetter, Sungero.Domain.Interfaces"; }
    }

    public override string DisplayValue
    {
      get { return this.Name; }
      set { this.Name = value; }
    }

    public new virtual global::GD.DCSGovernment.IProcessingRuleIncomingLetterState State
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetterState)base.State; }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::GD.DCSGovernment.Shared.ProcessingRuleIncomingLetterState(this);
    }

    public new virtual global::GD.DCSGovernment.IProcessingRuleIncomingLetterInfo Info
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetterInfo)base.Info; }
    }

    public new virtual global::GD.DCSGovernment.IProcessingRuleIncomingLetterAccessRights AccessRights
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetterAccessRights)base.AccessRights; }
    }

    protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
    {
      return new global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterAccessRights(this);
    }

    protected override global::Sungero.Domain.EntityFunctions CreateServerFunctions()
    {
      return new global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterFunctions(this);
    }

    protected override global::Sungero.Domain.Shared.EntityFunctions CreateSharedFunctions()
    {
      return new global::GD.DCSGovernment.Shared.ProcessingRuleIncomingLetterFunctions(this);
    }

    protected override object CreateHandlers() {
      return new global::GD.DCSGovernment.ProcessingRuleIncomingLetterServerHandlers(this);
    }

    protected override object CreateSharedHandlers() {
      return new global::GD.DCSGovernment.ProcessingRuleIncomingLetterSharedHandlers(this);
    }









    protected override global::Sungero.Domain.Shared.IChildEntityCollection<global::DirRX.DCTSIntegration.IProcessingRuleBasePerformers> CreatePerformersCollection()
    {
      return new global::Sungero.Domain.ChildEntityCollection<global::GD.DCSGovernment.IProcessingRuleIncomingLetterPerformers>() { RootEntity = this };
    }


    protected override global::Sungero.Domain.Shared.EntityCreatingFromServerHandler CreateCreatingFromServerHandler(
      global::Sungero.Domain.Shared.IEntity entitySource)
    {
      var instance = Sungero.Metadata.Services.AppliedTypesManager.CreateInstance("GD.DCSGovernment.ProcessingRuleIncomingLetterCreatingFromServerHandler", new object[] { (global::GD.DCSGovernment.IProcessingRuleIncomingLetter)entitySource, this.Info });
      if (instance != null)
        return (global::Sungero.Domain.Shared.EntityCreatingFromServerHandler)instance;

      return new global::GD.DCSGovernment.ProcessingRuleIncomingLetterCreatingFromServerHandler((global::GD.DCSGovernment.IProcessingRuleIncomingLetter)entitySource, this.Info);
    }

    #region Framework events




    #endregion


    public ProcessingRuleIncomingLetter()
    {
    }

  }
}

// ==================================================================
// ProcessingRuleIncomingLetterHandlers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment
{

  public partial class ProcessingRuleIncomingLetterFilteringServerHandler<T>
    : global::DirRX.DCTSIntegration.ProcessingRuleIncomingLetterFilteringServerHandler<T>  
    where T : class, global::GD.DCSGovernment.IProcessingRuleIncomingLetter
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState _filter
    {
      get
      {
        return (GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState)this.Filter;
      }
    }

    public ProcessingRuleIncomingLetterFilteringServerHandler(global::GD.DCSGovernment.IProcessingRuleIncomingLetterFilterState filter)
    : base(filter)
    {
    }

    protected ProcessingRuleIncomingLetterFilteringServerHandler()
    {
    }

    public override global::System.Linq.IQueryable<T> Filtering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.FilteringEventArgs e)
    {
      query = base.Filtering(query, e);
            return query;
    }


  }

  public partial class ProcessingRuleIncomingLetterUiFilteringServerHandler<T>
    : global::DirRX.DCTSIntegration.ProcessingRuleIncomingLetterUiFilteringServerHandler<T>
    where T : class, global::GD.DCSGovernment.IProcessingRuleIncomingLetter
  {
    public override global::System.Linq.IQueryable<T> Filtering(global::System.Linq.IQueryable<T> query, global::Sungero.Domain.UiFilteringEventArgs e)
    {
      query = base.Filtering(query, e);
            return query;
    }
  }

  public partial class ProcessingRuleIncomingLetterSearchDialogServerHandler : global::DirRX.DCTSIntegration.ProcessingRuleIncomingLetterSearchDialogServerHandler
   {
     private global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterSearchDialogModel _dialog
     {
       get
       {
         return (global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterSearchDialogModel)this.Dialog;
       }
     }

     public ProcessingRuleIncomingLetterSearchDialogServerHandler(global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterSearchDialogModel dialog)
       : base(dialog)
     {
     }
   }

  public partial class ProcessingRuleIncomingLetterServerHandlers : global::DirRX.DCTSIntegration.ProcessingRuleIncomingLetterServerHandlers
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetter _obj
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetter)this.Entity; }
    }

    public ProcessingRuleIncomingLetterServerHandlers(global::GD.DCSGovernment.IProcessingRuleIncomingLetter entity)
      : base(entity)
    {
    }
  }

  public partial class ProcessingRuleIncomingLetterCreatingFromServerHandler : global::DirRX.DCTSIntegration.ProcessingRuleIncomingLetterCreatingFromServerHandler
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetter _source
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetter)this.Source; }
    }

    private global::GD.DCSGovernment.IProcessingRuleIncomingLetterInfo _info
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetterInfo)this._Info; }
    }

    public ProcessingRuleIncomingLetterCreatingFromServerHandler(global::GD.DCSGovernment.IProcessingRuleIncomingLetter source, global::GD.DCSGovernment.IProcessingRuleIncomingLetterInfo info)
      : base(source, info)
    {
    }
  }

}

// ==================================================================
// ProcessingRuleIncomingLetterEventArgs.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{
}

// ==================================================================
// ProcessingRuleIncomingLetterAccessRights.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{
  public class ProcessingRuleIncomingLetterAccessRights : 
    DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterAccessRights, GD.DCSGovernment.IProcessingRuleIncomingLetterAccessRights
  {

    public ProcessingRuleIncomingLetterAccessRights(global::Sungero.Domain.Shared.IEntity entity) : base(entity)
    {
    }
  }

  public class ProcessingRuleIncomingLetterTypeAccessRights : 
    DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterTypeAccessRights, GD.DCSGovernment.IProcessingRuleIncomingLetterAccessRights
  {

    public ProcessingRuleIncomingLetterTypeAccessRights(global::System.Type entityType) : base(entityType)
    {
    }
  }
}

// ==================================================================
// ProcessingRuleIncomingLetterRepositoryImplementer.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{
    public class ProcessingRuleIncomingLetterRepositoryImplementer<T> : 
      global::DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterRepositoryImplementer<T>,
      global::GD.DCSGovernment.IProcessingRuleIncomingLetterRepositoryImplementer<T>
      where T : global::GD.DCSGovernment.IProcessingRuleIncomingLetter 
    {
       public new global::GD.DCSGovernment.IProcessingRuleIncomingLetterAccessRights AccessRights
       {
          get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetterAccessRights)base.AccessRights; }
       }

       public new global::GD.DCSGovernment.IProcessingRuleIncomingLetterInfo Info
       {
          get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetterInfo)base.Info; }
       }

       protected override global::Sungero.Domain.Shared.IEntityAccessRights CreateAccessRights()
       {
         return new global::GD.DCSGovernment.Server.ProcessingRuleIncomingLetterTypeAccessRights(typeof(T));
       }
    }
}

// ==================================================================
// ProcessingRuleIncomingLetterPanelNavigationFilters.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{
}

// ==================================================================
// ProcessingRuleIncomingLetterServerFunctions.g.cs
// ==================================================================

namespace GD.DCSGovernment.Server
{
  public partial class ProcessingRuleIncomingLetterFunctions : global::DirRX.DCTSIntegration.Server.ProcessingRuleIncomingLetterFunctions
  {
    private global::GD.DCSGovernment.IProcessingRuleIncomingLetter _obj
    {
      get { return (global::GD.DCSGovernment.IProcessingRuleIncomingLetter)this.Entity; }
    }

    public ProcessingRuleIncomingLetterFunctions(global::GD.DCSGovernment.IProcessingRuleIncomingLetter entity) : base(entity) { }
  }
}

// ==================================================================
// ProcessingRuleIncomingLetterFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Functions
{
  internal static class ProcessingRuleIncomingLetter
  {
  }
}

// ==================================================================
// ProcessingRuleIncomingLetterServerPublicFunctions.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Server
{
  public class ProcessingRuleIncomingLetterServerPublicFunctions : global::GD.DCSGovernment.Server.IProcessingRuleIncomingLetterServerPublicFunctions
  {
  }
}

// ==================================================================
// ProcessingRuleIncomingLetterQueries.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Queries
{
  public class ProcessingRuleIncomingLetter
  {
    private static global::Sungero.Domain.SqlQueryResolver resolver = new global::Sungero.Domain.SqlQueryResolver("GD.DCSGovernment.Server.ProcessingRuleIncomingLetter.ProcessingRuleIncomingLetterQueries.xml", System.Reflection.Assembly.GetExecutingAssembly());
  }
}
