
// ==================================================================
// Module.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Client
{
  public partial class DCSGovernmentModuleModule : global::Sungero.Domain.Shared.ModuleBase
  {
    public override global::System.Guid Id
    {
      get { return global::System.Guid.Parse("15db5ebc-a567-4d1a-b9d6-53fedc2030c0"); }
    }

    public override string Name
    {
      get { return "GD.DCSGovernmentModule"; }
    }

    public override void RegisterTypes()
    {
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("d574cc38-2354-46fa-85d6-686c525f182b"), new GD.DCSGovernmentModule.Shared.DocumentRegisterTaskInfo(typeof(global::GD.DCSGovernmentModule.IDocumentRegisterTask)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Client.IDocumentRegisterTaskClientPublicFunctions, global::GD.DCSGovernmentModule.Client.DocumentRegisterTaskClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IDocumentRegisterTaskSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskSharedPublicFunctions>();
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("2932f285-d458-4046-a392-87f6a50ba8ee"), new GD.DCSGovernmentModule.Shared.DocumentRegisterTaskObserversInfo(typeof(global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers)));
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("80051758-3f3f-4fcc-a772-f10c3c8e5bfd"), new GD.DCSGovernmentModule.Shared.ProcessingRuleRequestInfo(typeof(global::GD.DCSGovernmentModule.IProcessingRuleRequest)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Client.IProcessingRuleRequestClientPublicFunctions, global::GD.DCSGovernmentModule.Client.ProcessingRuleRequestClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IProcessingRuleRequestSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequestSharedPublicFunctions>();
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("3f8c9aa0-6e4f-4c0d-985c-9a0532c4d278"), new GD.DCSGovernmentModule.Shared.ProcessingRuleRequestPerformersInfo(typeof(global::GD.DCSGovernmentModule.IProcessingRuleRequestPerformers)));
      global::Sungero.Domain.Shared.EntityInfoRegister.RegisterEntityInfo(new global::System.Guid("9a576448-4a40-4dc6-8969-de3c210aec6a"), new GD.DCSGovernmentModule.Shared.RegistrationAssignmentInfo(typeof(global::GD.DCSGovernmentModule.IRegistrationAssignment)));
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Client.IRegistrationAssignmentClientPublicFunctions, global::GD.DCSGovernmentModule.Client.RegistrationAssignmentClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IRegistrationAssignmentSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.RegistrationAssignmentSharedPublicFunctions>();


      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.IDocumentRegisterTaskFilterState, global::GD.DCSGovernmentModule.Shared.DocumentRegisterTask.DocumentRegisterTaskFilterState>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.IProcessingRuleRequestFilterState, global::GD.DCSGovernmentModule.Shared.ProcessingRuleRequest.ProcessingRuleRequestFilterState>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.IRegistrationAssignmentFilterState, global::GD.DCSGovernmentModule.Shared.RegistrationAssignment.RegistrationAssignmentFilterState>();



      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Client.IModuleClientPublicFunctions, global::GD.DCSGovernmentModule.Client.ModuleClientPublicFunctions>();
      global::Sungero.Domain.Shared.ModuleManager.Instance.Container.RegisterType<global::GD.DCSGovernmentModule.Shared.IModuleSharedPublicFunctions, global::GD.DCSGovernmentModule.Shared.ModuleSharedPublicFunctions>();
    }
  }
}
