
// ==================================================================
// ProcessingRuleDocBasePerformers.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernment.Client
{
  public class ProcessingRuleDocBasePerformers :
    global::DirRX.DCTSIntegration.Client.ProcessingRuleDocBasePerformers, global::GD.DCSGovernment.IProcessingRuleDocBasePerformers
  {
    #region Fields and properties

    public static new readonly global::System.Guid ClassTypeGuid = global::System.Guid.Parse("ba791439-7977-48fc-8e2a-58341ffde32e");

    public override global::System.Guid TypeGuid
    {
      get { return global::GD.DCSGovernment.Client.ProcessingRuleDocBasePerformers.ClassTypeGuid; }
    }

    public override string TypeName
    {
      get { return "GD.DCSGovernment.IProcessingRuleDocBasePerformers, Sungero.Domain.Interfaces"; }
    }

    public new global::GD.DCSGovernment.IProcessingRuleDocBasePerformersState State
    {
      get
      {
        return (global::GD.DCSGovernment.IProcessingRuleDocBasePerformersState)base.State;
      }
    }

    protected override global::Sungero.Domain.Shared.IEntityState CreateState()
    {
      return new global::GD.DCSGovernment.Shared.ProcessingRuleDocBasePerformersState(this);
    }

    public new global::GD.DCSGovernment.IProcessingRuleDocBasePerformersInfo Info
    {
      get
      {
        return (global::GD.DCSGovernment.IProcessingRuleDocBasePerformersInfo)base.Info;
      }
    }










    #endregion

    #region Methods

    #endregion

    #region Framework events





    #endregion

    #region Constructors




    public ProcessingRuleDocBasePerformers()
    {








    }

    #endregion

  }
}
