
// ==================================================================
// DocumentRegisterTaskObserversState.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class DocumentRegisterTaskObserversState : 
    global::Sungero.Workflow.Shared.TaskObserversState, global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversState
  {
    public DocumentRegisterTaskObserversState(global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers entity) : base(entity) { }

    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertyStates Properties
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertyStates CreatePropertyStates(global::Sungero.Domain.Shared.IEntity entity)
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskObserversPropertyStates(entity);
    }


  }


  public class DocumentRegisterTaskObserversPropertyStates : 
    global::Sungero.Workflow.Shared.TaskObserversPropertyStates, global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertyStates
  {
            public new global::Sungero.Domain.Shared.IPropertyState<global::GD.DCSGovernmentModule.IDocumentRegisterTask> Task
            {
              get { return (global::Sungero.Domain.Shared.IPropertyState<global::GD.DCSGovernmentModule.IDocumentRegisterTask>)base.Task; }
            }

            protected override global::Sungero.Domain.Shared.IPropertyState<global::Sungero.Workflow.ITask> InternalTask
            {
              get { return this.GetPropertyState<global::GD.DCSGovernmentModule.IDocumentRegisterTask>("Task"); }
            }


    protected internal DocumentRegisterTaskObserversPropertyStates(global::Sungero.Domain.Shared.IEntity entity) : base(entity) { }
  }

  public class DocumentRegisterTaskObserversCollectionPropertyState<T> :
    global::Sungero.Workflow.Shared.TaskObserversCollectionPropertyState<T>, global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversCollectionPropertyState<T>
    where T : global::GD.DCSGovernmentModule.IDocumentRegisterTaskObservers
  {
    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversCollectionPropertyStates Properties
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversCollectionPropertyStates)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IChildEntityCollectionPropertyStates CreatePropertyStates()
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskObserversCollectionPropertyStates(this.ChildEntityMetadata);
    }

    protected internal DocumentRegisterTaskObserversCollectionPropertyState(global::Sungero.Domain.Shared.IEntity entity, string propertyName) : base(entity, propertyName) { }
  }

  public class DocumentRegisterTaskObserversCollectionPropertyStates :
    global::Sungero.Workflow.Shared.TaskObserversCollectionPropertyStates, global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversCollectionPropertyStates
  {

    protected internal DocumentRegisterTaskObserversCollectionPropertyStates(global::Sungero.Metadata.EntityMetadata childEntityMetadata) : base(childEntityMetadata) { }
  }
}

// ==================================================================
// DocumentRegisterTaskObserversInfo.g.cs
// ==================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD.DCSGovernmentModule.Shared
{
  public class DocumentRegisterTaskObserversInfo : 
    global::Sungero.Workflow.Shared.TaskObserversInfo, global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversInfo
  {
    public DocumentRegisterTaskObserversInfo(global::System.Type entityType) : base(entityType) { }

    public new global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertiesInfo Properties
    {
      get { return (global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertiesInfo)base.Properties; }
    }

    protected override global::Sungero.Domain.Shared.IEntityPropertiesInfo CreateEntityPropertiesInfo(global::System.Type entityType)
    {
      return new global::GD.DCSGovernmentModule.Shared.DocumentRegisterTaskObserversPropertiesInfo(entityType);
    }

  }

  public class DocumentRegisterTaskObserversPropertiesInfo : 
    global::Sungero.Workflow.Shared.TaskObserversPropertiesInfo, global::GD.DCSGovernmentModule.IDocumentRegisterTaskObserversPropertiesInfo
  {
        public new global::Sungero.Domain.Shared.INavigationPropertyInfo<global::GD.DCSGovernmentModule.IDocumentRegisterTaskInfo, global::GD.DCSGovernmentModule.IDocumentRegisterTask> Task
        {
          get
          {
             var propertyMetadata = this.GetPropertyMetadata<global::Sungero.Metadata.NavigationPropertyMetadata>("Task");
             return new global::Sungero.Domain.Shared.NavigationPropertyInfo<global::GD.DCSGovernmentModule.IDocumentRegisterTaskInfo, global::GD.DCSGovernmentModule.IDocumentRegisterTask>(propertyMetadata);
          }
        }


    protected internal DocumentRegisterTaskObserversPropertiesInfo(global::System.Type entityType) : base(entityType) { }
  }

}
